export const basicWordLists = {
    greetingsExpressions: [
        { english: "Hello", russian: "Здравствуйте", transliteration: "Zdravstvuytye", type: "formal" },
        { english: "Hello", russian: "Привет", transliteration: "Privyet", type: "informal" },
        { english: "Goodbye", russian: "До свидания", transliteration: "Do svidaniya", type: "formal" },
        { english: "Goodbye", russian: "Пока", transliteration: "Poka", type: "informal" },
        { english: "Yes", russian: "Да", transliteration: "Da" },
        { english: "No", russian: "Нет", transliteration: "Nyet" },
        { english: "Please", russian: "Пожалуйста", transliteration: "Pozhaluysta" },
        { english: "You're Welcome", russian: "Пожалуйста", transliteration: "Pozhaluysta" },
        { english: "Thank you", russian: "Спасибо", transliteration: "Spasibo" },
        { english: "Sorry", russian: "Извините", transliteration: "Izvinite", type: "formal" },
        { english: "Sorry", russian: "Прости", transliteration: "Prosti", type: "informal" },
        { english: "Excuse me", russian: "Извините", transliteration: "Izvinite" },
        { english: "How are you?", russian: "Как дела?", transliteration: "Kak dela?", type: "informal" },
        { english: "How are you?", russian: "Как Вы?", transliteration: "Kak Vy?", type: "formal" },
        { english: "What's your name?", russian: "Как тебя зовут?", transliteration: "Kak tebya zovut?", type: "informal" },
        { english: "What's your name?", russian: "Как Вас зовут?", transliteration: "Kak Vas zovut?", type: "formal" },
        { english: "Nice to meet you", russian: "Приятно познакомиться", transliteration: "Priyatno poznakomit'sya" },
        { english: "I don't understand", russian: "Я не понимаю", transliteration: "Ya ne ponimayu" },
        { english: "Could you repeat that?", russian: "Не могли бы вы повторить?", transliteration: "Ne mogli by vy povtorit?", type: "formal" },
        { english: "Could you repeat that?", russian: "Можешь повторить?", transliteration: "Mozhesh' povtorit?", type: "informal" },
        { english: "Where is the bathroom?", russian: "Где туалет?", transliteration: "Gde tualet?" },
    ],

    numbers: [
        { english: "1", russian: "Один", transliteration: "Odin" },
        { english: "2", russian: "Два", transliteration: "Dva" },
        { english: "3", russian: "Три", transliteration: "Tri" },
        { english: "4", russian: "Четыре", transliteration: "Chetyre" },
        { english: "5", russian: "Пять", transliteration: "Pyat'" },
        { english: "6", russian: "Шесть", transliteration: "Shest'" },
        { english: "7", russian: "Семь", transliteration: "Sem'" },
        { english: "8", russian: "Восемь", transliteration: "Vosem'" },
        { english: "9", russian: "Девять", transliteration: "Devyat'" },
        { english: "10", russian: "Десять", transliteration: "Desyat'" },
        { english: "11", russian: "Одиннадцать", transliteration: "Odinnadtsat'" },
        { english: "12", russian: "Двенадцать", transliteration: "Dvenadtsat'" },
        { english: "13", russian: "Тринадцать", transliteration: "Trinadtsat'" },
        { english: "14", russian: "Четырнадцать", transliteration: "Chetyrnadtsat'" },
        { english: "15", russian: "Пятнадцать", transliteration: "Pyatnadtsat'" },
        { english: "16", russian: "Шестнадцать", transliteration: "Shestnadtsat'" },
        { english: "17", russian: "Семнадцать", transliteration: "Semnadtsat'" },
        { english: "18", russian: "Восемнадцать", transliteration: "Vosemnadtsat'" },
        { english: "19", russian: "Девятнадцать", transliteration: "Devyatnadtsat'" },
        { english: "20", russian: "Двадцать", transliteration: "Dvadtsat'" },
        { english: "21", russian: "Двадцать один", transliteration: "Dvadtsat' odin" },
        { english: "22", russian: "Двадцать два", transliteration: "Dvadtsat' dva" },
        { english: "23", russian: "Двадцать три", transliteration: "Dvadtsat' tri" },
        { english: "24", russian: "Двадцать четыре", transliteration: "Dvadtsat' chetyre" },
        { english: "25", russian: "Двадцать пять", transliteration: "Dvadtsat' pyat'" },
        { english: "26", russian: "Двадцать шесть", transliteration: "Dvadtsat' shest'" },
        { english: "27", russian: "Двадцать семь", transliteration: "Dvadtsat' sem'" },
        { english: "28", russian: "Двадцать восемь", transliteration: "Dvadtsat' vosem'" },
        { english: "29", russian: "Двадцать девять", transliteration: "Dvadtsat' devyat'" },
        { english: "30", russian: "Тридцать", transliteration: "Tridtsat'" },
        { english: "40", russian: "Сорок", transliteration: "Sorok" },
        { english: "50", russian: "Пятьдесят", transliteration: "Pyat'desyat" },
        { english: "60", russian: "Шестьдесят", transliteration: "Shest'desyat" },
        { english: "70", russian: "Семьдесят", transliteration: "Sem'desyat" },
        { english: "80", russian: "Восемьдесят", transliteration: "Vosem'desyat" },
        { english: "90", russian: "Девяносто", transliteration: "Devyanosto" },
        { english: "100", russian: "Сто", transliteration: "Sto" },
    ],
    
    daysOfWeek: [
        { english: "Monday", russian: "Понедельник", transliteration: "Ponedel'nik" },
        { english: "Tuesday", russian: "Вторник", transliteration: "Vtornik" },
        { english: "Wednesday", russian: "Среда", transliteration: "Sreda" },
        { english: "Thursday", russian: "Четверг", transliteration: "Chetverg" },
        { english: "Friday", russian: "Пятница", transliteration: "Pyatnitsa" },
        { english: "Saturday", russian: "Суббота", transliteration: "Subbota" },
        { english: "Sunday", russian: "Воскресенье", transliteration: "Voskresen'ye" },
    ],
    
    monthsOfYear: [
        { english: "January", russian: "Январь", transliteration: "Yanvar'" },
        { english: "February", russian: "Февраль", transliteration: "Fevral'" },
        { english: "March", russian: "Март", transliteration: "Mart" },
        { english: "April", russian: "Апрель", transliteration: "Aprel'" },
        { english: "May", russian: "Май", transliteration: "May" },
        { english: "June", russian: "Июнь", transliteration: "Iyun'" },
        { english: "July", russian: "Июль", transliteration: "Iyul'" },
        { english: "August", russian: "Август", transliteration: "Avgust" },
        { english: "September", russian: "Сентябрь", transliteration: "Sentyabr'" },
        { english: "October", russian: "Октябрь", transliteration: "Oktyabr'" },
        { english: "November", russian: "Ноябрь", transliteration: "Noyabr'" },
        { english: "December", russian: "Декабрь", transliteration: "Dekabr'" },
    ],
    
    phrasesRelatedToDates: [
        { english: "Today", russian: "Сегодня", transliteration: "Sevodnya (soft v)" },
        { english: "Tomorrow", russian: "Завтра", transliteration: "Zavtra" },
        { english: "Yesterday", russian: "Вчера", transliteration: "Vchera" },
        { english: "Day after tomorrow", russian: "Послезавтра", transliteration: "Poslezavtra" },
        { english: "Day before yesterday", russian: "Позавчера", transliteration: "Pozavchera" },
        { english: "This week", russian: "На этой неделе", transliteration: "Na etoy nedele" },
        { english: "Last week", russian: "На прошлой неделе", transliteration: "Na proshloy nedele" },
        { english: "Next week", russian: "На следующей неделе", transliteration: "Na sleduyushchey nedele" },
        { english: "This month", russian: "В этом месяце", transliteration: "V etom mesyatse" },
        { english: "Last month", russian: "В прошлом месяце", transliteration: "V proshlom mesyatse" },
        { english: "Next month", russian: "В следующем месяце", transliteration: "V sleduyushchem mesyatse" },
        { english: "Year", russian: "Год", transliteration: "God" },
    ],
    
    colors: [
        { english: "White", russian: "Белый", transliteration: "Belyy" },
        { english: "Black", russian: "Черный", transliteration: "Chernyy" },
        { english: "Red", russian: "Красный", transliteration: "Krasnyy" },
        { english: "Blue", russian: "Синий", transliteration: "Siniy" },
        { english: "Green", russian: "Зеленый", transliteration: "Zelenyy" },
        { english: "Yellow", russian: "Желтый", transliteration: "Zheltiy" },
        { english: "Orange", russian: "Оранжевый", transliteration: "Oranzhevy" },
        { english: "Purple", russian: "Фиолетовый", transliteration: "Fioletovyy" },
        { english: "Brown", russian: "Коричневый", transliteration: "Korichnevyy" },
        { english: "Pink", russian: "Розовый", transliteration: "Rozovyy" },
        { english: "Gray", russian: "Серый", transliteration: "Seryy" },
        { english: "Gold", russian: "Золотой", transliteration: "Zolotoy" },
        { english: "Silver", russian: "Серебряный", transliteration: "Serebryanyy" },
    ],
    
    familyMembers: [
        { english: "Mother", russian: "Мама", transliteration: "Mama" },
        { english: "Father", russian: "Папа", transliteration: "Papa" },
        { english: "Brother", russian: "Брат", transliteration: "Brat" },
        { english: "Sister", russian: "Сестра", transliteration: "Sestra" },
        { english: "Grandmother", russian: "Бабушка", transliteration: "Babushka" },
        { english: "Grandfather", russian: "Дедушка", transliteration: "Dedushka" },
        { english: "Son", russian: "Сын", transliteration: "Syn" },
        { english: "Daughter", russian: "Дочьka", transliteration: "Dochka" },
        { english: "Uncle", russian: "Дядя", transliteration: "Dyadya" },
        { english: "Aunt", russian: "Тетя", transliteration: "Tetya" },
        { english: "Cousin", russian: "Двоюродный брат", transliteration: "Dvoyurodnyy brat", gender: 'male' },
        { english: "Cousin", russian: "Двоюродная сестра", transliteration: "Dvoyurodnaya sestra", gender: 'female' },
        { english: "Nephew", russian: "Племянник", transliteration: "Plemiannik" },
        { english: "Niece", russian: "Племянница", transliteration: "Plemiannitsa" },
        { english: "Wife", russian: "Жена", transliteration: "Zhena" },
        { english: "Husband", russian: "Муж", transliteration: "Muzh" },
    ],
    
    commonOccupations: [
        { english: "Teacher", russian: "Учитель", transliteration: "Uchitel" },
        { english: "Doctor", russian: "Врач", transliteration: "Vrach" },
        { english: "Engineer", russian: "Инженер", transliteration: "Inzhener" },
        { english: "Nurse", russian: "Медсестра", transliteration: "Medsestra" },
        { english: "Driver", russian: "Водитель", transliteration: "Voditel" },
        { english: "Jurist", russian: "Юрист", transliteration: "Yurist" },
        { english: "Lawyer", russian: "адвокат", transliteration: "Advocat" },
        { english: "Cook/Chef", russian: "Повар", transliteration: "Povar" },
        { english: "Artist", russian: "Художник", transliteration: "Khudozhnik" },
        { english: "Scientist", russian: "Ученый", transliteration: "Uchenyy" },
        { english: "Police Officer", russian: "Полицейский офицер", transliteration: "Politsiyskiy Ofitser" },
    ],
    
    descriptions: [
        { english: "Tall", russian: "Высокий", transliteration: "Vysokiy", gender: "male" },
        { english: "Tall", russian: "Высокaя", transliteration: "Vysokaya", gender: "female" },
        { english: "Short", russian: "Низкий", transliteration: "Nizkiy", gender: "male" },
        { english: "Short", russian: "Низкaя", transliteration: "Nizkya", gender: "female" },
        { english: "Young", russian: "Молодой", transliteration: "Molodoy", gender: "male" },
        { english: "Young", russian: "Молодaя", transliteration: "Molodaya", gender: "female" },
        { english: "Old", russian: "Старый", transliteration: "Staryy", gender: "male" },
        { english: "Old", russian: "Старaя", transliteration: "Staraya", gender: "female" },
        { english: "Handsome", russian: "Красивый", transliteration: "Krasivyy", gender: 'male' },
        { english: "Beautiful", russian: "Красивaя)", transliteration: "Krasivaya", gender: 'female' },
        { english: "Ugly", russian: "Уродливый", transliteration: "Urodlivyy", gender: 'male' },
        { english: "Ugly", russian: "Уродливaя", transliteration: "Urodlivaya", gender: 'female' },
        { english: "Thin", russian: "Худой", transliteration: "Khudoy", gender: 'male' },
        { english: "Thin", russian: "Худaя", transliteration: "Khudaya", gender: 'female'  },
        { english: "Fat", russian: "Толстый", transliteration: "Tolstyy", gender: 'male' },
        { english: "Fat", russian: "Толстaя", transliteration: "Tolstaya", gender: 'female'  },
        { english: "Strong", russian: "Сильный", transliteration: "Sil'nyy", gender: 'male' },
        { english: "Strong", russian: "Сильнaя", transliteration: "Sil'naya", gender: 'female'  },
        { english: "Weak", russian: "Слабый", transliteration: "Slabyy", gender: 'male' },
        { english: "Weak", russian: "Слабaя", transliteration: "Slabyaya", gender: 'female'  },
    ],
    
    commonVerbs: [
        { english: "Eat", russian: "Есть", transliteration: "Est'" },
        { english: "Go", russian: "Идти", transliteration: "Idti" },
        { english: "See", russian: "Видеть", transliteration: "Videt'" },
        { english: "Do/Make", russian: "Делать", transliteration: "Delat'" },
        { english: "Can (be able to)", russian: "Мoгy", transliteration: "Mugo'" },
        { english: "Have", russian: "Иметь", transliteration: "Imet'" },
        { english: "Speak/Talk", russian: "Говорить", transliteration: "Govorit'" },
        { english: "Understand", russian: "Понимать", transliteration: "Ponimat'" },
        { english: "Come", russian: "Приходить", transliteration: "Prihodit'" },
        { english: "Think", russian: "Думать", transliteration: "Dumat'" },
        { english: "Know", russian: "Знать", transliteration: "Znat'" },
        { english: "Live", russian: "Жить", transliteration: "Zhit'" },
        { english: "Work", russian: "Работать", transliteration: "Rabotat'" },
        { english: "Like/Love", russian: "Любить", transliteration: "Lyubit'" },
        { english: "Help", russian: "Помогать", transliteration: "Pomogat'" },
        { english: "Play", russian: "Играть", transliteration: "Igrat'" },
        { english: "Read", russian: "Читать", transliteration: "Chitat'" },
        { english: "Write", russian: "Писать", transliteration: "Pisat'" },
        { english: "Sit", russian: "Сидеть", transliteration: "Sidet'" },
        { english: "Stand", russian: "Стоять", transliteration: "Stoyat'" },
    ],
    
    commonAdjectives: [
        { english: "Big", russian: "Большой", transliteration: "Bol'shoy", gender: 'male' }, 
{ english: "Big", russian: "Большая", transliteration: "Bol'shaya", gender: 'female' },
{ english: "Small", russian: "Маленький", transliteration: "Malen'kiy", gender: 'male' },
{ english: "Small", russian: "Маленькая", transliteration: "Malen'kaya", gender: 'female' },
{ english: "Interesting", russian: "Интересный", transliteration: "Interesnyy", gender: 'male' },
{ english: "Interesting", russian: "Интересная", transliteration: "Interesnaya", gender: 'female' },
{ english: "Boring", russian: "Скучный", transliteration: "Skuchnyy", gender: 'male' },
{ english: "Boring", russian: "Скучная", transliteration: "Skuchnaya", gender: 'female' },
{ english: "Good", russian: "Хороший", transliteration: "Khoroshiy", gender: 'male' },
{ english: "Good", russian: "Хорошая", transliteration: "Khoroshaya", gender: 'female' },
{ english: "Bad", russian: "Плохой", transliteration: "Plokhoy", gender: 'male' },
{ english: "Bad", russian: "Плохая", transliteration: "Plokhaya", gender: 'female' },
{ english: "New", russian: "Новый", transliteration: "Novyy", gender: 'male' },
{ english: "New", russian: "Новая", transliteration: "Novaya", gender: 'female' },
{ english: "Delicious", russian: "Вкусный", transliteration: "Vkusnyy", gender: 'male' },
{ english: "Delicious", russian: "Вкусная", transliteration: "Vkusnaya", gender: 'female' },
{ english: "Disgusting", russian: "Отвратительный", transliteration: "Otvratitel'nyy", gender: 'male' },
{ english: "Disgusting", russian: "Отвратительная", transliteration: "Otvratitel'naya", gender: 'female' },
{ english: "Easy", russian: "Легкий", transliteration: "Legkiy", gender: 'male' },
{ english: "Easy", russian: "Легкая", transliteration: "Legkaya", gender: 'female' },
{ english: "Difficult", russian: "Сложный", transliteration: "Slozhnyy", gender: 'male' },
{ english: "Difficult", russian: "Сложная", transliteration: "Slozhnaya", gender: 'female' },
{ english: "Fast", russian: "Быстрый", transliteration: "Bystryy", gender: 'male' },
{ english: "Fast", russian: "Быстрая", transliteration: "Bystraya", gender: 'female' },
{ english: "Slow", russian: "Медленный", transliteration: "Medlennyy", gender: 'male' },
{ english: "Slow", russian: "Медленная", transliteration: "Medlennaya", gender: 'female' },
{ english: "Bright", russian: "Яркий", transliteration: "Yarkiy", gender: 'male' },
{ english: "Bright", russian: "Яркая", transliteration: "Yarkaya", gender: 'female' },
{ english: "Dark", russian: "Темный", transliteration: "Temnyy", gender: 'male' },
{ english: "Dark", russian: "Темная", transliteration: "Temnaya", gender: 'female' },

    ],
    
    foods: [
        { english: "Bread", russian: "Хлеб", transliteration: "Khleb" },
        { english: "Butter", russian: "Масло", transliteration: "Maslo" },
        { english: "Eggs", russian: "Яйца", transliteration: "Yaytsa" },
        { english: "Milk", russian: "Молоко", transliteration: "Moloko" },
        { english: "Cheese", russian: "Сыр", transliteration: "Syr" },
        { english: "Potato", russian: "Картошka", transliteration: "Kartoshka'" },
        { english: "Chicken", russian: "Курица", transliteration: "Kuritsa" },
        { english: "Fish", russian: "Рыба", transliteration: "Ryba" },
        { english: "Soup", russian: "Суп", transliteration: "Sup" },
        { english: "Porridge", russian: "Каша", transliteration: "Kasha" },
        { english: "Sausage", russian: "Колбаса", transliteration: "Kolbasa" },
        { english: "Salad", russian: "Салат", transliteration: "Salat" },
    ],
    
    drinks: [
        { english: "Tea", russian: "Чай", transliteration: "Chay" },
        { english: "Coffee", russian: "Кофе", transliteration: "Kofe" },
        { english: "Water", russian: "вода", transliteration: "Voda" },
        { english: "Mineral Water", russian: "Минеральная вода", transliteration: "Mineral'naya voda" },
        { english: "Juice", russian: "Сок", transliteration: "Sok" },
        { english: "Beer", russian: "Пиво", transliteration: "Pivo" },
        { english: "Wine", russian: "Вино", transliteration: "Vino" },
        { english: "Vodka", russian: "Водка", transliteration: "Vodka" },
    ],
    
    phrasesForOrderingAtARestaurant: [
        { english: "I would like to order...", russian: "Я бы хотел заказать...", transliteration: "Ya by khotel zakazat'..." },
        { english: "Could I have the menu, please?", russian: "Можно меню, пожалуйста?", transliteration: "Mozhno menyu, pozhaluysta?" },
        { english: "A table for two, please.", russian: "Столик на двоих, пожалуйста.", transliteration: "Stolik na dvoikh, pozhaluysta." },
        { english: "What do you recommend?", russian: "Что вы рекомендуете?", transliteration: "Chto vy rekomenduyete?" },
        { english: "Could I have the bill, please?", russian: "Можно счет, пожалуйста?", transliteration: "Mozhno schet, pozhaluysta?" },
        { english: "I am allergic to...", russian: "У меня аллергия на...", transliteration: "U menya allergiya na..." },
        { english: "Is this dish spicy?", russian: "Это блюдо острое?", transliteration: "Eto blyudo ostroe?" },
        { english: "Can I have some water, please?", russian: "Можно воды, пожалуйста?", transliteration: "Mozhno vody, pozhaluysta?" },
        { english: "Another one, please.", russian: "Еще один, пожалуйста.", transliteration: "Eshche odin, pozhaluysta." },
        { english: "A cup of coffee, please.", russian: "Чашку кофе, пожалуйста.", transliteration: "Chashku kofe, pozhaluysta." },
        { english: "I'll have a sandwich.", russian: "Я возьму бутерброд.", transliteration: "Ya voz'mu buterbrod." },
        { english: "Please give me this.", russian: "Пожалуйста, дайте мне это.", transliteration: "Pozhaluysta, dayte mne eto." },
        { english: "How much is the bread?", russian: "Сколько стоит хлеб?", transliteration: "Skol'ko stoit khleb?" },
        { english: "Could I get a glass of juice?", russian: "Можно стакан сока?", transliteration: "Mozhno stakan soka?" },
    ],
    
    namesOfPlaces: [
        { english: "Home", russian: "Дом", transliteration: "Dom" },
        { english: "School", russian: "Школа", transliteration: "Shkola" },
        { english: "University", russian: "Университет", transliteration: "Universitet" },
        { english: "Hospital", russian: "Больница", transliteration: "Bol'nitsa", type: 'formal' },
        { english: "Hospital", russian: "госпиталь", transliteration: "Gospital", type: 'informal' },
        { english: "Pharmacy", russian: "Аптека", transliteration: "Apteka" },
        { english: "Store/Shop", russian: "Магазин", transliteration: "Magazin" },
        { english: "Market", russian: "Рынок", transliteration: "Rynok" },
        { english: "Park", russian: "Парк", transliteration: "Park" },
        { english: "Museum", russian: "Музей", transliteration: "Muzei" },
        { english: "Theater", russian: "Театр", transliteration: "Teatr" },
        { english: "Cinema", russian: "Кинотеатр", transliteration: "Kinoteatr" },
        { english: "Library", russian: "Библиотека", transliteration: "Biblioteka" },
        { english: "Church", russian: "Церковь", transliteration: "Tserkov'" },
        { english: "Police Station", russian: "Полицейский участок", transliteration: "Politsiyskiy uchastok" },
        { english: "Restaurant", russian: "Ресторан", transliteration: "Restoran" },
        { english: "Café", russian: "Кафе", transliteration: "Kafe" },
        { english: "Hotel", russian: "Гостиница", transliteration: "Gostinitsa" },
        { english: "Bank", russian: "Банк", transliteration: "Bank" },
        { english: "Office", russian: "Офис", transliteration: "Ofis" },
        { english: "Gym", russian: "Спортзал", transliteration: "Sportzal" },
    ],
    
    directionWords: [
        { english: "Left", russian: "Налево", transliteration: "Nalevo" },
        { english: "Right", russian: "Направо", transliteration: "Napravo" },
        { english: "Straight", russian: "Прямо", transliteration: "Pryamo" },
        { english: "Back", russian: "Назад", transliteration: "Nazad" },
        { english: "Up", russian: "Вверх", transliteration: "Vverkh" },
        { english: "Down", russian: "Вниз", transliteration: "Vniz" },
        { english: "North", russian: "Север", transliteration: "Sever" },
        { english: "South", russian: "Юг", transliteration: "Yug" },
        { english: "East", russian: "Восток", transliteration: "Vostok" },
        { english: "West", russian: "Запад", transliteration: "Zapad" },
    ],
    
    directionPhrases: [
        { english: "Where is the nearest pharmacy?", russian: "Где ближайшая аптека?", transliteration: "Gde blizhayshaya apteka?" },
        { english: "How do I get to the museum?", russian: "Как мне добраться до музея?", transliteration: "Kak mne dobrat'sya do muzei?" },
        { english: "Is it far from here?", russian: "Это далеко отсюда?", transliteration: "Eto daleko otsyuda?" },
        { english: "Can you show me on the map?", russian: "Можете показать на карте?", transliteration: "Mozhete pokazat' na karte?" },
    ],
    
    timeRelatedWordsAndPhrases: [
        { english: "What time is it?", russian: "Который час?", transliteration: "Kotoryy chas?" },
        { english: "It's one o'clock.", russian: "Сейчас один час.", transliteration: "Seychas odin chas." },
        { english: "Minute", russian: "Минута", transliteration: "Minuta" },
        { english: "Hour", russian: "Час", transliteration: "Chas" },
        { english: "Day", russian: "День", transliteration: "Den'" },
        { english: "Week", russian: "Неделя", transliteration: "Nedelya" },
        { english: "Month", russian: "Месяц", transliteration: "Mesyats" },
        { english: "Year", russian: "Год", transliteration: "God" },
        { english: "Morning", russian: "Утро", transliteration: "Utro" },
        { english: "Afternoon", russian: "День", transliteration: "Den'" },
        { english: "Evening", russian: "Вечер", transliteration: "Vecher" },
        { english: "Night", russian: "Ночь", transliteration: "Noch'" },
    ],
    
    weatherTermsAndDescriptions: [
        { english: "Weather", russian: "Погода", transliteration: "Pogoda" },
        { english: "Sunny", russian: "Солнечно", transliteration: "Solnechno" },
        { english: "Cloudy", russian: "Облачно", transliteration: "Oblachno" },
        { english: "Rainy", russian: "Дождливо", transliteration: "Dozhd'livo" },
        { english: "Snowy", russian: "Снежно", transliteration: "Snezhno" },
        { english: "Windy", russian: "Ветрено", transliteration: "Vetreno" },
        { english: "Stormy", russian: "Бурно", transliteration: "Burno" },
        { english: "Foggy", russian: "Туманно", transliteration: "Tumanno" },
        { english: "Cold", russian: "Холодно", transliteration: "Kholodno" },
        { english: "Hot", russian: "Жарко", transliteration: "Zharko" },
        { english: "Warm", russian: "Тепло", transliteration: "Teplo" },
        { english: "Cool", russian: "Прохладно", transliteration: "Prokhladno" },
        { english: "Temperature", russian: "Температура", transliteration: "Temperatura" },
        { english: "Degree", russian: "Градус", transliteration: "Gradus" },
    ],
    
    askingAboutWeather: [
        { english: "What's the weather like today?", russian: "Какая сегодня погода?", transliteration: "Kakaya segodnya pogoda?" },
        { english: "Will it rain tomorrow?", russian: "Завтра будет дождь?", transliteration: "Zavtra budet dozhd'?" },
        { english: "Is it cold outside?", russian: "На улице холодно?", transliteration: "Na ulitse kholodno?" },
    ]
    
};

export const intermediateWordLists = {
    travelAndTransportation: {
        airportAndTrainStation: [
            { english: "Airport", russian: "Аэропорт", transliteration: "Aeroport" },
            { english: "Train Station", russian: "Вокзал", transliteration: "Vokzal" },
            { english: "Ticket", russian: "Билет", transliteration: "Bilet" },
            { english: "Passport", russian: "Паспорт", transliteration: "Pasport" },
            { english: "Luggage", russian: "Багаж", transliteration: "Bagazh" },
            { english: "Departure", russian: "Отправление", transliteration: "Otpravlenie" },
            { english: "Arrival", russian: "Прибытие", transliteration: "Pribytie" },
            { english: "Check-In", russian: "Регистрация", transliteration: "Registratsiya" },
            { english: "Customs", russian: "Таможня", transliteration: "Tamozhnya" },
            { english: "Security Check", russian: "Контроль безопасности", transliteration: "Kontrol' bezopasnosti" },
            { english: "Gate", russian: "Выход на посадку", transliteration: "Vykhod na posadku" },
            { english: "Boarding", russian: "Посадка", transliteration: "Posadka" },
            { english: "Flight", russian: "Рейс", transliteration: "Reys" },
            { english: "Delayed", russian: "Задержан", transliteration: "Zaderzhan" },
            { english: "Cancelled", russian: "Отменен", transliteration: "Otmenen" },
        ],
        commonPhrasesForBuyingTickets: [
            { english: "One ticket to Moscow, please.", russian: "Один билет до Москвы, пожалуйста.", transliteration: "Odin bilet do Moskvy, pozhaluysta." },
            { english: "Where can I buy a ticket?", russian: "Где я могу купить билет?", transliteration: "Gde ya mogu kupit' bilet?" },
            { english: "Is this seat available?", russian: "Это место свободно?", transliteration: "Eto mesto svobodno?" },
            { english: "I’d like to book a seat by the window.", russian: "Я бы хотел забронировать место у окна.", transliteration: "Ya by khotel zabronirovat' mesto u okna." },
        ],
        vocabularyForAskingForDirections: [
            { english: "Where is...?", russian: "Где находится...?", transliteration: "Gde nakhoditsya...?" },
            { english: "How do I get to...?", russian: "Как мне добраться до...?", transliteration: "Kak mne dobratsya do...?" },
            { english: "Is it far?", russian: "Это далеко?", transliteration: "Eto daleko?" },
            { english: "To the left.", russian: "Налево.", transliteration: "Nalevo." },
            { english: "To the right.", russian: "Направо.", transliteration: "Napravo." },
            { english: "Straight ahead.", russian: "Прямо.", transliteration: "Pryamo." },
            { english: "Map", russian: "Карта", transliteration: "Karta" },
        ],
        commonPhrasesUsedDuringTravel: [
            { english: "Can you show me on the map?", russian: "Можете показать на карте?", transliteration: "Mozhete pokazat' na karte?" },
            { english: "I need a taxi.", russian: "Мне нужно такси.", transliteration: "Mne nuzhno taksi." },
            { english: "How much does it cost?", russian: "Сколько это стоит?", transliteration: "Skol'ko eto stoit?" },
            { english: "Please stop here.", russian: "Остановитесь здесь, пожалуйста.", transliteration: "Ostanovites' zdes', pozhaluysta." },
            { english: "I am lost.", russian: "Я потерялся.", transliteration: "Ya poteryalsya/poteryalas'.", gender: "male"},
            { english: "I am lost.", russian: "Я потерялась.", transliteration: "Ya poteryalsya/poteryalas'.", gender: "female" },
            { english: "Does this train/bus go to...?", russian: "Этот поезд/автобус идет до...?", transliteration: "Etot poyezd/avtobus idet do...?" },
        ],
    },
    shoppingAndCommerce: {
        typesOfStores: [
            { english: "Supermarket", russian: "Супермаркет", transliteration: "Supermarket" },
            { english: "Department Store", russian: "Универмаг", transliteration: "Universam" },
            { english: "Pharmacy", russian: "Аптека", transliteration: "Apteka" },
            { english: "Bookstore", russian: "Книжный магазин", transliteration: "Knizhnyy magazin" },
            { english: "Clothing Store", russian: "Магазин одежды", transliteration: "Magazin odezhdy" },
            { english: "Shoe Store", russian: "Магазин обуви", transliteration: "Magazin obuvi" },
            { english: "Grocery Store", russian: "Продуктовый магазин", transliteration: "Produktovyy magazin" },
            { english: "Market", russian: "Рынок", transliteration: "Rynok" },
            { english: "Bakery", russian: "Булочная", transliteration: "Bulochnaya" },
            { english: "Butcher Shop", russian: "Мясная лавка", transliteration: "Myasnaya lavka" },
            { english: "Fish Market", russian: "Рыбный рынок", transliteration: "Rybn'y rynok" },
            { english: "Electronics Store", russian: "Магазин электроники", transliteration: "Magazin elektroniki" },
        ],
        shoppingVocabulary: [
            { english: "Price", russian: "Цена", transliteration: "Tsena" },
            { english: "Discount", russian: "Скидка", transliteration: "Skidka" },
            { english: "Sale", russian: "Распродажа", transliteration: "Rasprodazha" },
            { english: "Cashier", russian: "Кассир", transliteration: "Kassir" },
            { english: "Receipt", russian: "Чек", transliteration: "Chek" },
            { english: "Shopping Cart", russian: "Тележка", transliteration: "Telezhka" },
            { english: "Shopping Bag", russian: "Пакет", transliteration: "Paket" },
            { english: "Fitting Room", russian: "Примерочная", transliteration: "Primerochnaya" },
            { english: "Size", russian: "Размер", transliteration: "Razmer" },
            { english: "Exchange", russian: "Обмен", transliteration: "Obmen" },
            { english: "Return", russian: "Возврат", transliteration: "Vozvrat" },
        ],
        phrasesForBargainingAndDiscussingPrices: [
            { english: "How much is this?", russian: "Сколько это стоит?", transliteration: "Skol'ko eto stoit?" },
            { english: "Can you give a better price?", russian: "Можете сделать цену ниже?", transliteration: "Mozhete sdelat' tsenu nizhe?" },
            { english: "It's too expensive.", russian: "Это слишком дорого.", transliteration: "Eto slishkom dorogo." },
            { english: "Do you have anything cheaper?", russian: "У вас есть что-нибудь подешевле?", transliteration: "U vas est' chto-nibud' podeshevle?" },
            { english: "I'm just looking, thanks.", russian: "Я просто смотрю, спасибо.", transliteration: "Ya prosto smotryu, spasibo." },
            { english: "I would like to buy this.", russian: "Я бы хотел купить это.", transliteration: "Ya by khotel kupit' eto." },
            { english: "Can I pay by card?", russian: "Можно платить картой?", transliteration: "Mozhno platit' kartoy?" },
            { english: "Is there a discount for cash?", russian: "Есть ли скидка за наличные?", transliteration: "Est' li skidka za nalichnye?" },
        ],
        askingForHelp: [
            { english: "Where can I find...?", russian: "Где я могу найти...?", transliteration: "Gde ya mogu nayti...?" },
            { english: "Do you have this in another color?", russian: "У вас есть это в другом цвете?", transliteration: "U vas est' eto v drugom tsvete?" },
            { english: "I need help.", russian: "Мне нужна помощь.", transliteration: "Mne nuzhna pomoshch'", gender: "female" },
            { english: "I need help.", russian: "Мне нужен помощь.", transliteration: "Mne nuzhen pomoshch'", gender: "male" },
        ],
    },
    healthAndMedical: {
        medicalTerms: [
            { english: "Doctor", russian: "Доктор", transliteration: "Doktor" },
            { english: "Nurse", russian: "Медсестра", transliteration: "Medsestra" },
            { english: "Hospital", russian: "Больница", transliteration: "Bol'nitsa" },
            { english: "Clinic", russian: "Клиника", transliteration: "Klinika" },
            { english: "Pharmacy", russian: "Аптека", transliteration: "Apteka" },
            { english: "Medicine", russian: "Лекарство", transliteration: "Lekarstvo" },
            { english: "Prescription", russian: "Рецепт", transliteration: "Retsept" },
            { english: "Surgery", russian: "Хирургия", transliteration: "Khirurgiya" },
            { english: "Vaccine", russian: "Вакцина", transliteration: "Vaktsina" },
            { english: "Emergency Room (ER)", russian: "Приемное отделение", transliteration: "Priemnoe otdelenie" },
        ],
        symptoms: [
            { english: "Fever", russian: "Жар", transliteration: "Zhar" },
            { english: "Cough", russian: "Кашель", transliteration: "Kashel'" },
            { english: "Headache", russian: "Головная боль", transliteration: "Golovnaya bol'" },
            { english: "Stomachache", russian: "Боль в животе", transliteration: "Bol' v zhivote" },
            { english: "Nausea", russian: "Тошнота", transliteration: "Toshnota" },
            { english: "Dizziness", russian: "Головокружение", transliteration: "Golovokruzhenie" },
            { english: "Pain", russian: "Боль", transliteration: "Bol'" },
            { english: "Injury", russian: "Травма", transliteration: "Travma" },
            { english: "Allergy", russian: "Аллергия", transliteration: "Allergiya" },
            { english: "Cold", russian: "Простуда", transliteration: "Prostuda" },
        ],
        pharmacyEssentials: [
            { english: "Painkiller", russian: "Обезболивающее", transliteration: "Obezbolivayushchee" },
            { english: "Antibiotic", russian: "Антибиотик", transliteration: "Antibiotik" },
            { english: "Bandage", russian: "Бинт", transliteration: "Bint" },
            { english: "Antiseptic", russian: "Антисептик", transliteration: "Antiseptik" },
            { english: "Thermometer", russian: "Термометр", transliteration: "Termometr" },
            { english: "Cough Syrup", russian: "Сироп от кашля", transliteration: "Sirop ot kashlya" },
            { english: "Vitamins", russian: "Витамины", transliteration: "Vitaminy" },
        ],
        discussingEmergencies: [
            { english: "I need a doctor.", russian: "Мне нужен доктор.", transliteration: "Mne nuzhen doktor." },
            { english: "Call an ambulance!", russian: "Вызовите скорую помощь!", transliteration: "Vyzyvite skoruyu pomosh'!" },
            { english: "It's an emergency.", russian: "Это чрезвычайная ситуация.", transliteration: "Eto chrezvychaynaya situatsiya." },
            { english: "I'm allergic to...", russian: "У меня аллергия на...", transliteration: "U menya allergiya na..." },
            { english: "I feel sick.", russian: "Мне плохо.", transliteration: "Mne ploho." },
        ],
        talkingToDoctors: [
            { english: "What’s wrong with me?", russian: "Что со мной?", transliteration: "Chto so mnoy?" },
            { english: "It hurts here.", russian: "Здесь болит.", transliteration: "Zdes' bolit." },
            { english: "I have been feeling...", russian: "Я чувствую...", transliteration: "Ya chuvstvuyu..." },
            { english: "How long should I take this medicine?", russian: "Как долго мне принимать это лекарство?", transliteration: "Kak dolgo mne prinimat' eto lekarstvo?" },
            { english: "Are there any side effects?", russian: "Есть ли побочные эффекты?", transliteration: "Est' li pobochnye effekty?" },
        ],
    },
    schoolAndEducation: {
        academicSubjects: [
            { english: "Mathematics", russian: "Математика", transliteration: "Matematika" },
            { english: "Science", russian: "Наука", transliteration: "Nauka" },
            { english: "Biology", russian: "Биология", transliteration: "Biologiya" },
            { english: "Physics", russian: "Физика", transliteration: "Fizika" },
            { english: "Chemistry", russian: "Химия", transliteration: "Khimia" },
            { english: "Literature", russian: "Литература", transliteration: "Literatura" },
            { english: "History", russian: "История", transliteration: "Istoriya" },
            { english: "Geography", russian: "География", transliteration: "Geografiya" },
            { english: "Art", russian: "Искусство", transliteration: "Iskusstvo" },
            { english: "Physical Education", russian: "Физическая культура", transliteration: "Fizicheskaya kultura" },
            { english: "Foreign Languages", russian: "Иностранные языки", transliteration: "Inostrannye yazyki" },
            { english: "Music", russian: "Музыка", transliteration: "Muzyka" },
            { english: "Computer Science", russian: "Информатика", transliteration: "Informatika" },
        ],
        classroomItems: [
            { english: "Book", russian: "Книга", transliteration: "Kniga" },
            { english: "Notebook", russian: "Тетрадь", transliteration: "Tetrad'" },
            { english: "Pen", russian: "Ручка", transliteration: "Ruchka" },
            { english: "Pencil", russian: "Карандаш", transliteration: "Karandash" },
            { english: "Desk", russian: "Парта", transliteration: "Parta" },
            { english: "Chair", russian: "Стул", transliteration: "Stul" },
            { english: "Blackboard", russian: "Доска", transliteration: "Doska" },
            { english: "Chalk", russian: "Мел", transliteration: "Mel" },
            { english: "Marker", russian: "Маркер", transliteration: "Marker" },
            { english: "Eraser", russian: "Ластик", transliteration: "Lastik" },
            { english: "Blackboard Eraser", russian: "Стирка", transliteration: "Stirka" },
            { english: "Ruler", russian: "Линейка", transliteration: "Lineyka" },
            { english: "Backpack", russian: "Рюкзак", transliteration: "Ryukzak" },
        ],
        phrasesCommonlyUsedInAcademicSettings: [
            { english: "I have a question.", russian: "У меня вопрос.", transliteration: "U menya vopros." },
            { english: "What page are we on?", russian: "На какой мы странице?", transliteration: "Na kakoy my stranitse?" },
            { english: "I didn’t understand the homework.", russian: "Я не понял(а) домашнее задание.", transliteration: "Ya ne ponyal/a domashnee zadanie." },
            { english: "Can you help me with this?", russian: "Можешь мне помочь с этим?", transliteration: "Mozhesh' mne pomoch' s etim?" },
            { english: "When is the assignment due?", russian: "Когда сдавать задание?", transliteration: "Kogda sdavat' zadanie?" },
            { english: "I need to go to the library.", russian: "Мне нужно идти в библиотеку.", transliteration: "Mne nuzhno idti v biblioteku." },
            { english: "Let’s study together.", russian: "Давай учиться вместе.", transliteration: "Davay uchitsya vmeste." },
            { english: "Who is the teacher for this class?", russian: "Кто преподаватель этого класса?", transliteration: "Kto prepodavatel' etogo klassa?" },
            { english: "I passed/failed the test.", russian: "Я сдал(а)/не сдал(а) тест.", transliteration: "Ya sdal/a/ne sdal/a test." },
            { english: "Can I borrow your notes?", russian: "Можно взять твои конспекты?", transliteration: "Mozhno vzyat' tvoi konspekty?" },
        ],
    },
    workAndProfessions: {
        jobTitles: [
            { english: "Doctor", russian: "Доктор", transliteration: "Doktor" },
            { english: "Teacher", russian: "Учитель", transliteration: "Uchitel" },
            { english: "Engineer", russian: "Инженер", transliteration: "Inzhener" },
            { english: "Nurse", russian: "Медсестра", transliteration: "Medsestra" },
            { english: "Lawyer", russian: "Адвокат", transliteration: "Advokat" },
            { english: "Accountant", russian: "Бухгалтер", transliteration: "Bukhgalter" },
            { english: "Manager", russian: "Менеджер", transliteration: "Menedzher" },
            { english: "Programmer", russian: "Программист", transliteration: "Programmist" },
            { english: "Salesperson", russian: "Продавец", transliteration: "Prodavets" },
            { english: "Chef", russian: "Повар", transliteration: "Povar" },
            { english: "Mechanic", russian: "Механик", transliteration: "Mekhanik" },
            { english: "Artist", russian: "Художник", transliteration: "Khudozhnik" },
            { english: "Architect", russian: "Архитектор", transliteration: "Arkhitektor" },
        ],
        officeItems: [
            { english: "Computer", russian: "Компьютер", transliteration: "Kompyuter" },
            { english: "Printer", russian: "Принтер", transliteration: "Printer" },
            { english: "Fax machine", russian: "Факс", transliteration: "Faks" },
            { english: "Desk", russian: "Рабочий стол", transliteration: "Rabochiy stol" },
            { english: "Chair", russian: "Стул", transliteration: "Stul" },
            { english: "File", russian: "Папка", transliteration: "Papka" },
            { english: "Pen", russian: "Ручка", transliteration: "Ruchka" },
            { english: "Pencil", russian: "Карандаш", transliteration: "Karandash" },
            { english: "Notebook", russian: "Записная книжка", transliteration: "Zapisnaya knizhka" },
            { english: "Calendar", russian: "Календарь", transliteration: "Kalendar" },
        ],
        jobApplicationProcess: [
            { english: "Resume/CV", russian: "Резюме", transliteration: "Rezyume" },
            { english: "Cover letter", russian: "Сопроводительное письмо", transliteration: "Soprovoditel'noe pismo" },
            { english: "Job interview", russian: "Собеседование", transliteration: "Sobesedovanie" },
            { english: "Hire", russian: "Нанять", transliteration: "Nanyat'" },
            { english: "Fire", russian: "Уволить", transliteration: "Uvolit'" },
            { english: "Salary", russian: "Зарплата", transliteration: "Zarplata" },
            { english: "Contract", russian: "Контракт", transliteration: "Kontrakt" },
            { english: "Benefits", russian: "Льготы", transliteration: "L'goty" },
        ],
        phrasesForProfessionalInteractions: [
            { english: "Can we schedule a meeting?", russian: "Можем мы запланировать встречу?", transliteration: "Mozhem my zaplanirovat' vstrechu?" },
            { english: "I will send you the report by email.", russian: "Я отправлю вам отчет по электронной почте.", transliteration: "Ya otpravlyu vam otchet po elektronnoy pochte." },
            { english: "Please, review the document.", russian: "Пожалуйста, просмотрите документ.", transliteration: "Pozhaluysta, prosmotrite dokument." },
            { english: "What is the deadline for this project?", russian: "Какой срок для этого проекта?", transliteration: "Kakoy srok dlya etogo proekta?" },
            { english: "I am out of the office today.", russian: "Я сегодня не в офисе.", transliteration: "Ya segodnya ne v ofise." },
            { english: "Do you have any questions about the presentation?", russian: "У вас есть вопросы к презентации?", transliteration: "U vas est' voprosy k prezentatsii?" },
            { english: "Let's discuss it during our next meeting.", russian: "Давайте обсудим это на нашей следующей встрече.", transliteration: "Davayte obsudim eto na nashey sleduyushchey vstreche." },
            { english: "Thank you for your cooperation.", russian: "Спасибо за сотрудничество.", transliteration: "Spasibo za sotrudnichestvo." },
        ],
    },
    sportsAndLeisure: {
        sportsNames: [
            { english: "Soccer", russian: "Футбол", transliteration: "Futbol" },
            { english: "Basketball", russian: "Баскетбол", transliteration: "Basketbol" },
            { english: "Volleyball", russian: "Волейбол", transliteration: "Voleybol" },
            { english: "Tennis", russian: "Теннис", transliteration: "Tennis" },
            { english: "Swimming", russian: "Плавание", transliteration: "Plavanie" },
            { english: "Gymnastics", russian: "Гимнастика", transliteration: "Gimnastika" },
            { english: "Figure Skating", russian: "Фигурное катание", transliteration: "Figurnoe katanie" },
            { english: "Hockey", russian: "Хоккей", transliteration: "Khokkey" },
            { english: "Boxing", russian: "Бокс", transliteration: "Boks" },
            { english: "Skiing", russian: "Лыжный спорт", transliteration: "Lyzhnyy sport" },
        ],
        hobbies: [
            { english: "Reading", russian: "Чтение", transliteration: "Chtenie" },
            { english: "Drawing", russian: "Рисование", transliteration: "Risovanie" },
            { english: "Dancing", russian: "Танцы", transliteration: "Tantsy" },
            { english: "Singing", russian: "Пение", transliteration: "Penie" },
            { english: "Fishing", russian: "Рыбалка", transliteration: "Rybalka" },
            { english: "Photography", russian: "Фотография", transliteration: "Fotografiya" },
            { english: "Cooking", russian: "Кулинария", transliteration: "Kulinariya" },
            { english: "Gardening", russian: "Садоводство", transliteration: "Sadovodstvo" },
        ],
        equipmentUsedInVariousActivities: [
            { english: "Ball", russian: "Мяч", transliteration: "Myach" },
            { english: "Racket", russian: "Ракетка", transliteration: "Raketka" },
            { english: "Swimsuit", russian: "Купальник", transliteration: "Kupal'nik" },
            { english: "Skates", russian: "Коньки", transliteration: "Kon'ki" },
            { english: "Skis", russian: "Лыжи", transliteration: "Lyzhi" },
            { english: "Helmet", russian: "Шлем", transliteration: "Shlem" },
            { english: "Gloves", russian: "Перчатки", transliteration: "Perchatki" },
            { english: "Net", russian: "Сетка", transliteration: "Setka" },
            { english: "Fishing rod", russian: "Удочка", transliteration: "Udochka" },
            { english: "Camera", russian: "Фотоаппарат", transliteration: "Fotoapparat" },
        ],
        phrasesForDiscussingGamesAndSports: [
            { english: "Who won the game?", russian: "Кто выиграл игру?", transliteration: "Kto vyigral igru?" },
            { english: "Let’s play soccer.", russian: "Давай поиграем в футбол.", transliteration: "Davay poigraem v futbol." },
            { english: "I go to the gym three times a week.", russian: "Я хожу в спортзал три раза в неделю.", transliteration: "Ya khozhu v sportzal tri raza v nedelyu." },
            { english: "Do you want to join me for a swim?", russian: "Хочешь со мной поплавать?", transliteration: "Khocheh so mnoy poplavat'?" },
            { english: "I enjoy skiing in the winter.", russian: "Я люблю кататься на лыжах зимой.", transliteration: "Ya lyublyu katat'sya na lyzhakh zimoy." },
            { english: "Let's set up the net for volleyball.", russian: "Давай установим сетку для волейбола.", transliteration: "Davay ustanovim setku dlya voleybola." },
        ],
    },
    natureAndEnvironment: {
        landscapes: [
            { english: "Forest", russian: "Лес", transliteration: "Les" },
            { english: "Mountain", russian: "Гора", transliteration: "Gora" },
            { english: "River", russian: "Река", transliteration: "Reka" },
            { english: "Sea", russian: "Море", transliteration: "More" },
            { english: "Ocean", russian: "Океан", transliteration: "Okean" },
            { english: "Lake", russian: "Озеро", transliteration: "Ozero" },
            { english: "Beach", russian: "Пляж", transliteration: "Plyazh" },
            { english: "Desert", russian: "Пустыня", transliteration: "Pustynya" },
            { english: "Valley", russian: "Долина", transliteration: "Dolina" },
            { english: "Hill", russian: "Холм", transliteration: "Kholm" },
        ],
        weatherPatterns: [
            { english: "Rain", russian: "Дождь", transliteration: "Dozhd'" },
            { english: "Snow", russian: "Снег", transliteration: "Sneg" },
            { english: "Fog", russian: "Туман", transliteration: "Tuman" },
            { english: "Wind", russian: "Ветер", transliteration: "Veter" },
            { english: "Storm", russian: "Буря", transliteration: "Burya" },
            { english: "Thunderstorm", russian: "Гроза", transliteration: "Groza" },
            { english: "Breeze", russian: "Бриз", transliteration: "Briz" },
            { english: "Heatwave", russian: "Жара", transliteration: "Zhara" },
            { english: "Drought", russian: "Засуха", transliteration: "Zasukha" },
            { english: "Flood", russian: "Наводнение", transliteration: "Navodnenie" },
        ],
        floraAndFauna: [
            { english: "Tree", russian: "Дерево", transliteration: "Derevo" },
            { english: "Flower", russian: "Цветок", transliteration: "Tsvetok" },
            { english: "Grass", russian: "Трава", transliteration: "Trava" },
            { english: "Bush", russian: "Куст", transliteration: "Kust" },
            { english: "Leaf", russian: "Лист", transliteration: "List" },
            { english: "Bird", russian: "Птица", transliteration: "Ptitsa" },
            { english: "Fish", russian: "Рыба", transliteration: "Ryba" },
            { english: "Insect", russian: "Насекомое", transliteration: "Nasekomoe" },
            { english: "Mammal", russian: "Млекопитающее", transliteration: "Mlekopitayushchee" },
            { english: "Reptile", russian: "Рептилия", transliteration: "Reptiliya" },
        ],
        environmentalIssues: [
            { english: "Pollution", russian: "Загрязнение", transliteration: "Zagryaznenie" },
            { english: "Global warming", russian: "Глобальное потепление", transliteration: "Global'noe poteplenie" },
            { english: "Deforestation", russian: "Вырубка лесов", transliteration: "Vyrubka lesov" },
            { english: "Wildlife conservation", russian: "Охрана дикой природы", transliteration: "Ohrana dikoy prirody" },
            { english: "Recycling", russian: "Переработка", transliteration: "Pererabotka" },
            { english: "Sustainable development", russian: "Устойчивое развитие", transliteration: "Ustoychivoe razvitie" },
            { english: "Ecosystem", russian: "Экосистема", transliteration: "Ekosistema" },
            { english: "Biodiversity", russian: "Биоразнообразие", transliteration: "Bioraznoobrazie" },
            { english: "Waste management", russian: "Управление отходами", transliteration: "Upravlenie otkhodami" },
            { english: "Energy conservation", russian: "Энергосбережение", transliteration: "Energosberezhenie" },
        ],
    },
    technologyAndInternet: {
        computerAndHardware: [
            { english: "Computer", russian: "Компьютер", transliteration: "Kompyuter" },
            { english: "Laptop", russian: "Ноутбук", transliteration: "Noutbuk" },
            { english: "Tablet", russian: "Планшет", transliteration: "Planshet" },
            { english: "Monitor", russian: "Монитор", transliteration: "Monitor" },
            { english: "Keyboard", russian: "Клавиатура", transliteration: "Klaviatura" },
            { english: "Mouse", russian: "Мышь", transliteration: "Mysh'" },
            { english: "Printer", russian: "Принтер", transliteration: "Printer" },
            { english: "USB drive", russian: "Флешка", transliteration: "Fleshka" },
            { english: "Hard drive", russian: "Жесткий диск", transliteration: "Zhestkiy disk" },
            { english: "Charger", russian: "Зарядное устройство", transliteration: "Zaryadnoe ustroystvo" },
        ],
        internetAndNetworking: [
            { english: "Internet", russian: "Интернет", transliteration: "Internet" },
            { english: "Website", russian: "Сайт", transliteration: "Sayt" },
            { english: "Link", russian: "Ссылка", transliteration: "Ssylka" },
            { english: "Search engine", russian: "Поисковая система", transliteration: "Poiskovaya sistema" },
            { english: "Email", russian: "Электронная почта", transliteration: "Elektronnaya pochta" },
            { english: "Wi-Fi", russian: "Вай-фай", transliteration: "Wi-Fi" },
            { english: "Router", russian: "Роутер", transliteration: "Router" },
            { english: "Browser", russian: "Браузер", transliteration: "Brauzer" },
            { english: "Download", russian: "Скачать", transliteration: "Skachat'" },
            { english: "Upload", russian: "Загрузить", transliteration: "Zagruzit'" },
        ],
        socialMediaAndOnlineCommunication: [
            { english: "Social media", russian: "Социальные сети", transliteration: "Sotsial'nye seti" },
            { english: "Post", russian: "Пост", transliteration: "Post" },
            { english: "Comment", russian: "Комментарий", transliteration: "Kommentariy" },
            { english: "Message", russian: "Сообщение", transliteration: "Soobshchenie" },
            { english: "Friend", russian: "Друг", transliteration: "Drug" },
            { english: "Follower", russian: "Подписчик", transliteration: "Podpischik" },
            { english: "Like", russian: "Лайк", transliteration: "Layk" },
            { english: "Share", russian: "Поделиться", transliteration: "Podelit'sya" },
            { english: "Profile", russian: "Профиль", transliteration: "Profil'" },
            { english: "Hashtag", russian: "Хештег", transliteration: "Kheshteg" },
        ],
        techSupportIssues: [
            { english: "Error", russian: "Ошибка", transliteration: "Oshibka" },
            { english: "Bug", russian: "Баг", transliteration: "Bag" },
            { english: "Crash", russian: "Сбой", transliteration: "Sboy" },
            { english: "Update", russian: "Обновление", transliteration: "Obnovlenie" },
            { english: "Backup", russian: "Резервная копия", transliteration: "Rezervnaya kopiya" },
            { english: "Virus", russian: "Вирус", transliteration: "Virus" },
            { english: "Malware", russian: "Вредоносное ПО", transliteration: "Vredonosnoe PO" },
            { english: "Password", russian: "Пароль", transliteration: "Parol" },
            { english: "Support", russian: "Поддержка", transliteration: "Podderzhka" },
            { english: "Settings", russian: "Настройки", transliteration: "Nastroyki" },
        ],
    },
    artsAndEntertainment: {
        moviesAndCinema: [
            { english: "Movie", russian: "Фильм", transliteration: "Film" },
            { english: "Cinema", russian: "Кинотеатр", transliteration: "Kinoteatr" },
            { english: "Actor", russian: "Актер", transliteration: "Akter" },
            { english: "Actress", russian: "Актриса", transliteration: "Aktrisa" },
            { english: "Director", russian: "Режиссер", transliteration: "Rezhisser" },
            { english: "Screenplay", russian: "Сценарий", transliteration: "Stsenariy" },
            { english: "Scene", russian: "Сцена", transliteration: "Stsena" },
            { english: "Trailer", russian: "Трейлер", transliteration: "Treiler" },
            { english: "Soundtrack", russian: "Саундтрек", transliteration: "Saundtrek" },
            { english: "Genre", russian: "Жанр", transliteration: "Zhanr" },
        ],
        music: [
            { english: "Music", russian: "Музыка", transliteration: "Muzyka" },
            { english: "Song", russian: "Песня", transliteration: "Pesnya" },
            { english: "Singer", russian: "Певец", transliteration: "Pevets" },
            { english: "Band", russian: "Группа", transliteration: "Gruppa" },
            { english: "Concert", russian: "Концерт", transliteration: "Kontsert" },
        ],
        literature: [
            { english: "Book", russian: "Книга", transliteration: "Kniga" },
            { english: "Author", russian: "Автор", transliteration: "Avtor" },
            { english: "Novel", russian: "Роман", transliteration: "Roman" },
            { english: "Poetry", russian: "Поэзия", transliteration: "Poeziya" },
            { english: "Chapter", russian: "Глава", transliteration: "Glava" },
            { english: "Plot", russian: "Сюжет", transliteration: "Syuzhet" },
            { english: "Character", russian: "Персонаж", transliteration: "Personazh" },
            { english: "Edition", russian: "Издание", transliteration: "Izdanie" },
            { english: "Publisher", russian: "Издатель", transliteration: "Izdatel'" },
            { english: "Literary critique", russian: "Литературная критика", transliteration: "Literaturnaya kritika" },
        ],
        culturalEvents: [
            { english: "Exhibition", russian: "Выставка", transliteration: "Vystavka" },
            { english: "Theater", russian: "Театр", transliteration: "Teatr" },
            { english: "Performance", russian: "Спектакль", transliteration: "Spektakl'" },
            { english: "Festival", russian: "Фестиваль", transliteration: "Festival'" },
            { english: "Gallery", russian: "Галерея", transliteration: "Galereya" },
            { english: "Art", russian: "Искусство", transliteration: "Iskusstvo" },
            { english: "Sculpture", russian: "Скульптура", transliteration: "Skulptura" },
            { english: "Dance", russian: "Танец", transliteration: "Tanets" },
            { english: "Opera", russian: "Опера", transliteration: "Opera" },
            { english: "Ballet", russian: "Балет", transliteration: "Ballet" },
        ],
    },
    foodPreparationAndCooking: {
        cookingUtensils: [
            { english: "Knife", russian: "Нож", transliteration: "Nozh" },
            { english: "Fork", russian: "Вилка", transliteration: "Vilka" },
            { english: "Spoon", russian: "Ложка", transliteration: "Lozhka" },
            { english: "Spatula", russian: "Лопатка", transliteration: "Lopatka" },
            { english: "Whisk", russian: "Венчик", transliteration: "Venchik" },
            { english: "Peeler", russian: "Овощечистка", transliteration: "Ovoshchechistka" },
            { english: "Grater", russian: "Терка", transliteration: "Terka" },
            { english: "Cutting Board", russian: "Разделочная доска", transliteration: "Razdelochnaya doska" },
            { english: "Measuring Cup", russian: "Мерный стакан", transliteration: "Mernyy stakan" },
            { english: "Mixing Bowl", russian: "Миска для смешивания", transliteration: "Miska dlya smeshivaniya" },
        ],
        cookingMethods: [
            { english: "Boil", russian: "Варить", transliteration: "Varit'" },
            { english: "Fry", russian: "Жарить", transliteration: "Zharit'" },
            { english: "Bake", russian: "Печь", transliteration: "Pech'" },
            { english: "Grill", russian: "Гриль", transliteration: "Gril'" },
            { english: "Steam", russian: "Парить", transliteration: "Parit'" },
            { english: "Roast", russian: "Запекать", transliteration: "Zapekat'" },
            { english: "Simmer", russian: "Томить", transliteration: "Tomit'" },
            { english: "Blend", russian: "Смешивать", transliteration: "Smeshivat'" },
            { english: "Chop", russian: "Резать", transliteration: "Rezat'" },
            { english: "Slice", russian: "Нарезать ломтиками", transliteration: "Narezat' lomtikami" },
        ],
        ingredients: [
            { english: "Salt", russian: "Соль", transliteration: "Sol'" },
            { english: "Pepper", russian: "Перец", transliteration: "Perets" },
            { english: "Oil", russian: "Масло", transliteration: "Maslo" },
            { english: "Butter", russian: "Сливочное масло", transliteration: "Slivochnoe maslo" },
            { english: "Sugar", russian: "Сахар", transliteration: "Sakhar" },
            { english: "Flour", russian: "Мука", transliteration: "Muka" },
            { english: "Egg", russian: "Яйцо", transliteration: "Yaytso" },
            { english: "Milk", russian: "Молоко", transliteration: "Moloko" },
            { english: "Garlic", russian: "Чеснок", transliteration: "Chesnok" },
            { english: "Onion", russian: "Лук", transliteration: "Luk" },
        ],
        phrasesForCooking: [
            { english: "How long should I cook this?", russian: "Как долго это готовить?", transliteration: "Kak dolgo eto gotovit'?" },
            { english: "What temperature should I use?", russian: "Какую температуру использовать?", transliteration: "Kakuyu temperaturu ispol'zovat'?" },
            { english: "How do I prepare this dish?", russian: "Как приготовить это блюдо?", transliteration: "Kak prigotovit' eto blyudo?" },
            { english: "Do you have a recipe for this?", russian: "У вас есть рецепт для этого?", transliteration: "U vas est' retsept dlya etogo?" },
            { english: "Can you help me cook this?", russian: "Можете помочь мне это приготовить?", transliteration: "Mozhete pomoch' mne eto prigotovit'?" },
            { english: "What ingredients do I need?", russian: "Какие ингредиенты мне нужны?", transliteration: "Kakie ingredienty mne nuzhny?" },
            { english: "Stir continuously.", russian: "Помешивайте непрерывно.", transliteration: "Pomeshivayte nepreryvno." },
            { english: "Let it cool down.", russian: "Дайте ему остыть.", transliteration: "Dayte yemu ostyt'" },
            { english: "Add salt to taste.", russian: "Добавьте соль по вкусу.", transliteration: "Dobav'te sol' po vkusu." },
            { english: "Chop the vegetables finely.", russian: "Мелко нарежьте овощи.", transliteration: "Melko narezh'te ovoshchi." },
        ],
    },
    holidaysAndCelebrations: {
        holidays: [
            { english: "New Year", russian: "Новый год", transliteration: "Novyy god" },
            { english: "Christmas", russian: "Рождество", transliteration: "Rozhdestvo" },
            { english: "Easter", russian: "Пасха", transliteration: "Paskha" },
            { english: "Thanksgiving", russian: "День благодарения", transliteration: "Den' blagodareniya" },
            { english: "Halloween", russian: "Хэллоуин", transliteration: "Khellouin" },
            { english: "Valentine's Day", russian: "День святого Валентина", transliteration: "Den' svyatogo Valentina" },
            { english: "Independence Day", russian: "День независимости", transliteration: "Den' nezavisimosti" },
            { english: "Victory Day", russian: "День Победы", transliteration: "Den' Pobedy" },
            { english: "International Women's Day", russian: "Международный женский день", transliteration: "Mezhdunarodnyy zhenskiy den'" },
            { english: "Labor Day", russian: "День труда", transliteration: "Den' truda" },
        ],
        celebrationActivities: [
            { english: "Party", russian: "Вечеринка", transliteration: "Vecherinka" },
            { english: "Parade", russian: "Парад", transliteration: "Parad" },
            { english: "Feast", russian: "Пир", transliteration: "Pir" },
            { english: "Fireworks", russian: "Фейерверк", transliteration: "Feyerverk" },
            { english: "Gift exchange", russian: "Обмен подарками", transliteration: "Obmen podarkami" },
            { english: "Costume", russian: "Костюм", transliteration: "Kostyum" },
            { english: "Dance", russian: "Танец", transliteration: "Tanets" },
            { english: "Song", russian: "Песня", transliteration: "Pesnya" },
            { english: "Tradition", russian: "Традиция", transliteration: "Traditsiya" },
            { english: "Decoration", russian: "Украшение", transliteration: "Ukrashenie" },
        ],
        phrasesForCelebrations: [
            { english: "Happy New Year!", russian: "С новым годом!", transliteration: "S novym godom!" },
            { english: "Merry Christmas!", russian: "Счастливого Рождества!", transliteration: "Schastlivogo Rozhdestva!" },
            { english: "Happy Easter!", russian: "Счастливой Пасхи!", transliteration: "Schastlivoy Paskhi!" },
            { english: "Happy Thanksgiving!", russian: "С Днем благодарения!", transliteration: "S Dnyom blagodareniya!" },
            { english: "Happy Halloween!", russian: "Счастливого Хэллоуина!", transliteration: "Schastlivogo Khellouina!" },
            { english: "Happy Valentine's Day!", russian: "С Днем святого Валентина!", transliteration: "S Dnyom svyatogo Valentina!" },
            { english: "Happy Independence Day!", russian: "С Днем независимости!", transliteration: "S Dnyom nezavisimosti!" },
            { english: "Happy Victory Day!", russian: "С Днем Победы!", transliteration: "S Dnyom Pobedy!" },
            { english: "Happy Women's Day!", russian: "С Международным женским днем!", transliteration: "S Mezhdunarodnym zhenskim dnyom!" },
            { english: "Happy Labor Day!", russian: "С Днем труда!", transliteration: "S Dnyom truda!" },
        ],
    },
    emotionsAndRelationships: {
        emotions: [
            { english: "Happy", russian: "Счастливый", transliteration: "Schastlivyy", gender: 'male' },
            { english: "Happy", russian: "Счастливая", transliteration: "Schastlivaya", gender: 'female' },
            { english: "Sad", russian: "Грустный", transliteration: "Grustnyy", gender: 'male' },
            { english: "Sad", russian: "Грустная", transliteration: "Grustnaya", gender: 'female' },
            { english: "Angry", russian: "Злой", transliteration: "Zloy", gender: 'male' },
            { english: "Angry", russian: "Злая", transliteration: "Zlaya", gender: 'female' },
            { english: "Excited", russian: "Взволнованный", transliteration: "Vzvolnovannyy", gender: 'male' },
            { english: "Excited", russian: "Взволнованная", transliteration: "Vzvolnovannaya", gender: 'female' },
            { english: "Afraid", russian: "Испуганный", transliteration: "Ispugannyy", gender: 'male' },
            { english: "Afraid", russian: "Испуганная", transliteration: "Ispugannaya", gender: 'female' },
            { english: "Surprised", russian: "Удивленный", transliteration: "Udivlennyy", gender: 'male' },
            { english: "Surprised", russian: "Удивленная", transliteration: "Udivlennaya", gender: 'female' },
            { english: "Nervous", russian: "Нервный", transliteration: "Nervnyy", gender: 'male' },
            { english: "Nervous", russian: "Нервная", transliteration: "Nervnaya", gender: 'female' },
            { english: "Bored", russian: "Скучающий", transliteration: "Skuchayushchiy", gender: 'male' },
            { english: "Bored", russian: "Скучающая", transliteration: "Skuchayushchaya", gender: 'female' },
            { english: "Confident", russian: "Уверенный", transliteration: "Uverennyy", gender: 'male' },
            { english: "Confident", russian: "Уверенная", transliteration: "Uverennaya", gender: 'female' },
            { english: "Lonely", russian: "Одинокий", transliteration: "Odinokiy", gender: 'male' },
            { english: "Lonely", russian: "Одинокая", transliteration: "Odinokaya", gender: 'female' },
        ],
        relationships: [
            { english: "Friend", russian: "Друг", transliteration: "Drug" },
            { english: "Family", russian: "Семья", transliteration: "Sem'ya" },
            { english: "Parents", russian: "Родители", transliteration: "Roditeli" },
            { english: "Sibling", russian: "Брат или сестра", transliteration: "Brat ili sestra" },
            { english: "Partner", russian: "Партнер", transliteration: "Partner" },
            { english: "Husband", russian: "Супруг", transliteration: "Suprug", gender: "male" },
            { english: "Wife", russian: "Супруга", transliteration: "Supruga", gender: "female" },
            { english: "Child", russian: "Ребенок", transliteration: "Rebenok" },
            { english: "Colleague", russian: "Коллега", transliteration: "Kollega" },
            { english: "Neighbor", russian: "Сосед", transliteration: "Sosed" },
            { english: "Acquaintance", russian: "Знакомый", transliteration: "Znakomyy" },
        ],
        phrasesForEmotions: [
            { english: "I feel happy.", russian: "Я чувствую себя счастливым.", transliteration: "Ya chuvstvuyu sebya schastlivym." },
            { english: "I am sad.", russian: "Мне грустно.", transliteration: "Mne grustno." },
            { english: "You look angry.", russian: "Ты выглядишь злым.", transliteration: "Ty viglyadish' zlym." },
            { english: "She is excited.", russian: "Она взволнована.", transliteration: "Ona vzvolnovana." },
            { english: "He is afraid.", russian: "Он испуган.", transliteration: "On ispugan." },
            { english: "Are you surprised?", russian: "Ты удивлен?", transliteration: "Ty udivlen?" },
            { english: "I feel nervous.", russian: "Я нервничаю.", transliteration: "Ya nervnichayu." },
            { english: "He looks bored.", russian: "Он выглядит скучающим.", transliteration: "On viglyadit skuchayushchim." },
            { english: "She is confident.", russian: "Она уверена.", transliteration: "Ona uverena." },
            { english: "I feel lonely.", russian: "Я чувствую себя одиноким.", transliteration: "Ya chuvstvuyu sebya odinokim." },
        ],
        phrasesForRelationships: [
            { english: "He is my friend.", russian: "Он мой друг.", transliteration: "On moy drug." },
            { english: "She is my sister.", russian: "Она моя сестра.", transliteration: "Ona moya sestra." },
            { english: "They are my parents.", russian: "Они мои родители.", transliteration: "Oni moi roditeli." },
            { english: "He is my brother.", russian: "Он мой брат.", transliteration: "On moy brat." },
            { english: "She is my partner.", russian: "Она моя партнер.", transliteration: "Ona moya partner." },
            { english: "He is my spouse.", russian: "Он мой супруг.", transliteration: "On moy suprug." },
            { english: "She is my spouse.", russian: "Она моя супруга.", transliteration: "Ona moya supruga." },
            { english: "They are my children.", russian: "Они мои дети.", transliteration: "Oni moi deti." },
            { english: "He is my colleague.", russian: "Он мой коллега.", transliteration: "On moy kollega." },
            { english: "She is my neighbor.", russian: "Она моя соседка.", transliteration: "Ona moya sosedka." },
        ],
    },
    lawAndGovernment: {
        governmentTerms: [
            { english: "Government", russian: "Правительство", transliteration: "Pravitel'stvo" },
            { english: "President", russian: "Президент", transliteration: "Prezident" },
            { english: "Prime Minister", russian: "Премьер-министр", transliteration: "Prem'yer-ministr" },
            { english: "Parliament", russian: "Парламент", transliteration: "Parlament" },
            { english: "Senate", russian: "Сенат", transliteration: "Senat" },
            { english: "Congress", russian: "Конгресс", transliteration: "Kongress" },
            { english: "Election", russian: "Выборы", transliteration: "Vybory" },
            { english: "Vote", russian: "Голосовать", transliteration: "Golosovat'" },
            { english: "Law", russian: "Закон", transliteration: "Zakon" },
            { english: "Policy", russian: "Политика", transliteration: "Politika" },
        ],
        legalTerms: [
            { english: "Court", russian: "Суд", transliteration: "Sud" },
            { english: "Judge", russian: "Судья", transliteration: "Sud'ya" },
            { english: "Lawyer", russian: "Адвокат", transliteration: "Advokat" },
            { english: "Jury", russian: "Жюри", transliteration: "Zhuri" },
            { english: "Trial", russian: "Судебный процесс", transliteration: "Sudebnyy protsess" },
            { english: "Verdict", russian: "Вердикт", transliteration: "Verdikt" },
            { english: "Sentence", russian: "Приговор", transliteration: "Prigovor" },
            { english: "Defendant", russian: "Ответчик", transliteration: "Otvetchik" },
            { english: "Plaintiff", russian: "Истец", transliteration: "Istets" },
            { english: "Evidence", russian: "Доказательства", transliteration: "Dokazatel'stva" },
        ],
        lawEnforcement: [
            { english: "Police", russian: "Полиция", transliteration: "Politsiya" },
            { english: "Officer", russian: "Офицер", transliteration: "Ofitser" },
            { english: "Detective", russian: "Детектив", transliteration: "Detektiv" },
            { english: "Arrest", russian: "Арест", transliteration: "Arest" },
            { english: "Crime", russian: "Преступление", transliteration: "Prestuplenie" },
            { english: "Investigation", russian: "Расследование", transliteration: "Rassledovanie" },
            { english: "Prison", russian: "Тюрьма", transliteration: "Tyur'ma" },
            { english: "Inmate", russian: "Заключенный", transliteration: "Zaklyuchennyy" },
            { english: "Parole", russian: "Условно-досрочное освобождение", transliteration: "Uslovno-dosrochnoe osvobozhdenie" },
            { english: "Bail", russian: "Залог", transliteration: "Zalog" },
        ],
        phrasesForLegalAndGovernmentMatters: [
            { english: "I need a lawyer.", russian: "Мне нужен адвокат.", transliteration: "Mne nuzhen advokat." },
            { english: "What are my rights?", russian: "Какие у меня права?", transliteration: "Kakie u menya prava?" },
            { english: "You are under arrest.", russian: "Вы арестованы.", transliteration: "Vy arestovany." },
            { english: "I want to speak to my attorney.", russian: "Я хочу поговорить со своим адвокатом.", transliteration: "Ya khochu pogovorit' so svoim advokatom." },
            { english: "The defendant is guilty.", russian: "Ответчик виновен.", transliteration: "Otvetchik vinoven." },
            { english: "The defendant is not guilty.", russian: "Ответчик не виновен.", transliteration: "Otvetchik ne vinoven." },
            { english: "The court is in session.", russian: "Судебное заседание началось.", transliteration: "Sudebnoe zasedanie nachalos'." },
            { english: "The trial is postponed.", russian: "Судебный процесс отложен.", transliteration: "Sudebnyy protsess otlozhen." },
            { english: "I plead not guilty.", russian: "Я не признаю себя виновным.", transliteration: "Ya ne priznay u sebya vinovnym." },
            { english: "The evidence is clear.", russian: "Доказательства ясны.", transliteration: "Dokazatel'stva yasny." },
        ],
    },
    realEstateAndHousing: {
        typesOfHousing: [
            { english: "Apartment", russian: "Квартира", transliteration: "Kvartira" },
            { english: "House", russian: "Дом", transliteration: "Dom" },
            { english: "Condominium", russian: "Кондоминиум", transliteration: "Kondominium" },
            { english: "Townhouse", russian: "Таунхаус", transliteration: "Taunkhaus" },
            { english: "Villa", russian: "Вилла", transliteration: "Villa" },
            { english: "Studio", russian: "Студия", transliteration: "Studiya" },
            { english: "Duplex", russian: "Дуплекс", transliteration: "Duplex" },
            { english: "Cottage", russian: "Коттедж", transliteration: "Kottedzh" },
            { english: "Bungalow", russian: "Бунгало", transliteration: "Bungalo" },
            { english: "Penthouse", russian: "Пентхаус", transliteration: "Pentkhaus" },
        ],
        partsOfAHouse: [
            { english: "Living room", russian: "Гостиная", transliteration: "Gostinaya" },
            { english: "Kitchen", russian: "Кухня", transliteration: "Kukhnya" },
            { english: "Bedroom", russian: "Спальня", transliteration: "Spalnya" },
            { english: "Bathroom", russian: "Ванная комната", transliteration: "Vannaya komnata" },
            { english: "Dining room", russian: "Столовая", transliteration: "Stolovaya" },
            { english: "Garage", russian: "Гараж", transliteration: "Garazh" },
            { english: "Basement", russian: "Подвал", transliteration: "Podval" },
            { english: "Attic", russian: "Чердак", transliteration: "Cherdak" },
            { english: "Garden", russian: "Сад", transliteration: "Sad" },
            { english: "Balcony", russian: "Балкон", transliteration: "Balkon" },
        ],
        realEstateTerms: [
            { english: "For sale", russian: "Продается", transliteration: "Prodayetsya" },
            { english: "For rent", russian: "Сдается в аренду", transliteration: "Sdayetsya v arendu" },
            { english: "Lease", russian: "Договор аренды", transliteration: "Dogovor arendy" },
            { english: "Mortgage", russian: "Ипотека", transliteration: "Ipoteka" },
            { english: "Real estate agent", russian: "Агент по недвижимости", transliteration: "Agent po nedvizhimosti" },
            { english: "Landlord", russian: "Арендодатель", transliteration: "Arendodatel'" },
            { english: "Tenant", russian: "Арендатор", transliteration: "Arendator" },
            { english: "Deposit", russian: "Залог", transliteration: "Zalog" },
            { english: "Inspection", russian: "Осмотр", transliteration: "Osmotr" },
            { english: "Utilities", russian: "Коммунальные услуги", transliteration: "Kommunal'nye uslugi" },
        ],
        phrasesForRealEstate: [
            { english: "How much is the rent?", russian: "Сколько стоит аренда?", transliteration: "Skol'ko stoit arenda?" },
            { english: "Is the house furnished?", russian: "Дом меблирован?", transliteration: "Dom meblirovan?" },
            { english: "When is the rent due?", russian: "Когда нужно платить аренду?", transliteration: "Kogda nuzhno platit' arendu?" },
            { english: "Can I see the apartment?", russian: "Можно посмотреть квартиру?", transliteration: "Mozhno posmotret' kvartiru?" },
            { english: "What is included in the rent?", russian: "Что включено в аренду?", transliteration: "Chto vklyucheno v arendu?" },
            { english: "Are pets allowed?", russian: "Можно с животными?", transliteration: "Mozhno s zhivotnymi?" },
            { english: "How long is the lease?", russian: "На какой срок договор аренды?", transliteration: "Na kakoy srok dogovor arendy?" },
            { english: "Is there a parking space?", russian: "Есть ли парковочное место?", transliteration: "Est' li parkovochnoye mesto?" },
            { english: "What is the security deposit?", russian: "Каков размер залога?", transliteration: "Kakov razmer zaloga?" },
            { english: "How can I contact the landlord?", russian: "Как я могу связаться с арендодателем?", transliteration: "Kak ya mogu svyazat'sya s arendodatelem?" },
        ],
    },
    historyAndCulture: {
        historicalPeriods: [
            { english: "Ancient history", russian: "Древняя история", transliteration: "Drevnyaya istoriya" },
            { english: "Middle Ages", russian: "Средневековье", transliteration: "Srednevekov'ye" },
            { english: "Renaissance", russian: "Возрождение", transliteration: "Vozrozhdenie" },
            { english: "Industrial Revolution", russian: "Промышленная революция", transliteration: "Promyshlennaya revolyutsiya" },
            { english: "Modern history", russian: "Новая история", transliteration: "Novaya istoriya" },
            { english: "World War I", russian: "Первая мировая война", transliteration: "Pervaya mirovaya voyna" },
            { english: "World War II", russian: "Вторая мировая война", transliteration: "Vtoraya mirovaya voyna" },
            { english: "Cold War", russian: "Холодная война", transliteration: "Kholodnaya voyna" },
            { english: "Post-war era", russian: "Послевоенный период", transliteration: "Poslevoennyy period" },
            { english: "Information Age", russian: "Информационная эра", transliteration: "Informatsionnaya era" },
        ],
        historicalFigures: [
            { english: "Pharaoh", russian: "Фараон", transliteration: "Faraon" },
            { english: "Emperor", russian: "Император", transliteration: "Imperator" },
            { english: "King", russian: "Король", transliteration: "Korol'" },
            { english: "Queen", russian: "Королева", transliteration: "Koroleva" },
            { english: "President", russian: "Президент", transliteration: "Prezident" },
            { english: "General", russian: "Генерал", transliteration: "General" },
            { english: "Revolutionary", russian: "Революционер", transliteration: "Revolyutsioner" },
            { english: "Explorer", russian: "Исследователь", transliteration: "Issledovatel'" },
            { english: "Scientist", russian: "Ученый", transliteration: "Uchenyy" },
            { english: "Artist", russian: "Художник", transliteration: "Khudozhnik" },
        ],
        culturalConcepts: [
            { english: "Tradition", russian: "Традиция", transliteration: "Traditsiya" },
            { english: "Custom", russian: "Обычай", transliteration: "Obychay" },
            { english: "Festival", russian: "Фестиваль", transliteration: "Festival'" },
            { english: "Ritual", russian: "Ритуал", transliteration: "Ritual" },
            { english: "Myth", russian: "Миф", transliteration: "Mif" },
            { english: "Legend", russian: "Легенда", transliteration: "Legenda" },
            { english: "Heritage", russian: "Наследие", transliteration: "Nasledie" },
            { english: "Folklore", russian: "Фольклор", transliteration: "Fol'klor" },
            { english: "Art", russian: "Искусство", transliteration: "Iskusstvo" },
            { english: "Music", russian: "Музыка", transliteration: "Muzyka" },
        ],
        phrasesForHistoryAndCulture: [
            { english: "What is the history of this place?", russian: "Какова история этого места?", transliteration: "Kakova istoriya etogo mesta?" },
            { english: "Who are the important historical figures?", russian: "Кто важные исторические личности?", transliteration: "Kto vazhnyye istoricheskiye lichnosti?" },
            { english: "What are the cultural traditions?", russian: "Каковы культурные традиции?", transliteration: "Kakovy kul'turnyye traditsii?" },
            { english: "Can you tell me about the local customs?", russian: "Вы можете рассказать мне о местных обычаях?", transliteration: "Vy mozhete rasskazat' mne o mestnykh obychaikh?" },
            { english: "Is there a museum nearby?", russian: "Есть ли поблизости музей?", transliteration: "Est' li poblizosti muzey?" },
            { english: "What festivals are celebrated here?", russian: "Какие фестивали празднуются здесь?", transliteration: "Kakie festivali prazdnuyutsya zdes'?" },
            { english: "What is the significance of this monument?", russian: "Каково значение этого памятника?", transliteration: "Kakovo znachenie etogo pamyatnika?" },
            { english: "This is a UNESCO World Heritage site.", russian: "Это объект Всемирного наследия ЮНЕСКО.", transliteration: "Eto obyekt Vsemirnogo naslediya YUNESKO." },
            { english: "Can you explain the local folklore?", russian: "Вы можете объяснить местный фольклор?", transliteration: "Vy mozhete obyasnit' mestnyy fol'klor?" },
            { english: "What are the famous works of art here?", russian: "Какие здесь известные произведения искусства?", transliteration: "Kakie zdes' izvestnyye proizvedeniya iskusstva?" },
        ],
    },
}