export const basicWordLists = {
    greetingsExpressions: [
        { english: "Hello", russian: "Здравствуйте", transliteration: "Zdravstvuytye", type: "formal" },
        { english: "Hello", russian: "Привет", transliteration: "Privyet", type: "informal" },
        { english: "Goodbye", russian: "До свидания", transliteration: "Do svidaniya", type: "formal" },
        { english: "Goodbye", russian: "Пока", transliteration: "Poka", type: "informal" },
        { english: "Yes", russian: "Да", transliteration: "Da" },
        { english: "No", russian: "Нет", transliteration: "Nyet" },
        { english: "Please", russian: "Пожалуйста", transliteration: "Pozhaluysta" },
        { english: "Thank you", russian: "Спасибо", transliteration: "Spasibo" },
        { english: "Sorry", russian: "Извините", transliteration: "Izvinite", type: "formal" },
        { english: "Sorry", russian: "Прости", transliteration: "Prosti", type: "informal" },
        { english: "Excuse me", russian: "Извините", transliteration: "Izvinite" },
        { english: "How are you?", russian: "Как дела?", transliteration: "Kak dela?", type: "informal" },
        { english: "How are you?", russian: "Как Вы?", transliteration: "Kak Vy?", type: "formal" },
        { english: "What's your name?", russian: "Как тебя зовут?", transliteration: "Kak tebya zovut?", type: "informal" },
        { english: "What's your name?", russian: "Как Вас зовут?", transliteration: "Kak Vas zovut?", type: "formal" },
        { english: "Nice to meet you", russian: "Приятно познакомиться", transliteration: "Priyatno poznakomit'sya" },
        { english: "I don't understand", russian: "Я не понимаю", transliteration: "Ya ne ponimayu" },
        { english: "Could you repeat that?", russian: "Не могли бы вы повторить?", transliteration: "Ne mogli by vy povtorit?", type: "formal" },
        { english: "Could you repeat that?", russian: "Можешь повторить?", transliteration: "Mozhesh' povtorit?", type: "informal" },
        { english: "Where is the bathroom?", russian: "Где туалет?", transliteration: "Gde tualet?" },
    ],

    numbers: [
        { english: "1", russian: "Один", transliteration: "Odin" },
        { english: "2", russian: "Два", transliteration: "Dva" },
        { english: "3", russian: "Три", transliteration: "Tri" },
        { english: "4", russian: "Четыре", transliteration: "Chetyre" },
        { english: "5", russian: "Пять", transliteration: "Pyat'" },
        { english: "6", russian: "Шесть", transliteration: "Shest'" },
        { english: "7", russian: "Семь", transliteration: "Sem'" },
        { english: "8", russian: "Восемь", transliteration: "Vosem'" },
        { english: "9", russian: "Девять", transliteration: "Devyat'" },
        { english: "10", russian: "Десять", transliteration: "Desyat'" },
        { english: "11", russian: "Одиннадцать", transliteration: "Odinnadtsat'" },
        { english: "12", russian: "Двенадцать", transliteration: "Dvenadtsat'" },
        { english: "13", russian: "Тринадцать", transliteration: "Trinadtsat'" },
        { english: "14", russian: "Четырнадцать", transliteration: "Chetyrnadtsat'" },
        { english: "15", russian: "Пятнадцать", transliteration: "Pyatnadtsat'" },
        { english: "16", russian: "Шестнадцать", transliteration: "Shestnadtsat'" },
        { english: "17", russian: "Семнадцать", transliteration: "Semnadtsat'" },
        { english: "18", russian: "Восемнадцать", transliteration: "Vosemnadtsat'" },
        { english: "19", russian: "Девятнадцать", transliteration: "Devyatnadtsat'" },
        { english: "20", russian: "Двадцать", transliteration: "Dvadtsat'" },
        { english: "21", russian: "Двадцать один", transliteration: "Dvadtsat' odin" },
        { english: "22", russian: "Двадцать два", transliteration: "Dvadtsat' dva" },
        { english: "23", russian: "Двадцать три", transliteration: "Dvadtsat' tri" },
        { english: "24", russian: "Двадцать четыре", transliteration: "Dvadtsat' chetyre" },
        { english: "25", russian: "Двадцать пять", transliteration: "Dvadtsat' pyat'" },
        { english: "26", russian: "Двадцать шесть", transliteration: "Dvadtsat' shest'" },
        { english: "27", russian: "Двадцать семь", transliteration: "Dvadtsat' sem'" },
        { english: "28", russian: "Двадцать восемь", transliteration: "Dvadtsat' vosem'" },
        { english: "29", russian: "Двадцать девять", transliteration: "Dvadtsat' devyat'" },
        { english: "30", russian: "Тридцать", transliteration: "Tridtsat'" },
        { english: "40", russian: "Сорок", transliteration: "Sorok" },
        { english: "50", russian: "Пятьдесят", transliteration: "Pyat'desyat" },
        { english: "60", russian: "Шестьдесят", transliteration: "Shest'desyat" },
        { english: "70", russian: "Семьдесят", transliteration: "Sem'desyat" },
        { english: "80", russian: "Восемьдесят", transliteration: "Vosem'desyat" },
        { english: "90", russian: "Девяносто", transliteration: "Devyanosto" },
        { english: "100", russian: "Сто", transliteration: "Sto" },
    ],
    
    daysOfWeek: [
        { english: "Monday", russian: "Понедельник", transliteration: "Ponedel'nik" },
        { english: "Tuesday", russian: "Вторник", transliteration: "Vtornik" },
        { english: "Wednesday", russian: "Среда", transliteration: "Sreda" },
        { english: "Thursday", russian: "Четверг", transliteration: "Chetverg" },
        { english: "Friday", russian: "Пятница", transliteration: "Pyatnitsa" },
        { english: "Saturday", russian: "Суббота", transliteration: "Subbota" },
        { english: "Sunday", russian: "Воскресенье", transliteration: "Voskresen'ye" },
    ],
    
    monthsOfYear: [
        { english: "January", russian: "Январь", transliteration: "Yanvar'" },
        { english: "February", russian: "Февраль", transliteration: "Fevral'" },
        { english: "March", russian: "Март", transliteration: "Mart" },
        { english: "April", russian: "Апрель", transliteration: "Aprel'" },
        { english: "May", russian: "Май", transliteration: "May" },
        { english: "June", russian: "Июнь", transliteration: "Iyun'" },
        { english: "July", russian: "Июль", transliteration: "Iyul'" },
        { english: "August", russian: "Август", transliteration: "Avgust" },
        { english: "September", russian: "Сентябрь", transliteration: "Sentyabr'" },
        { english: "October", russian: "Октябрь", transliteration: "Oktyabr'" },
        { english: "November", russian: "Ноябрь", transliteration: "Noyabr'" },
        { english: "December", russian: "Декабрь", transliteration: "Dekabr'" },
    ],
    
    phrasesRelatedToDates: [
        { english: "Today", russian: "Сегодня", transliteration: "Segodnya" },
        { english: "Tomorrow", russian: "Завтра", transliteration: "Zavtra" },
        { english: "Yesterday", russian: "Вчера", transliteration: "Vchera" },
        { english: "Day after tomorrow", russian: "Послезавтра", transliteration: "Poslezavtra" },
        { english: "Day before yesterday", russian: "Позавчера", transliteration: "Pozavchera" },
        { english: "This week", russian: "На этой неделе", transliteration: "Na etoy nedele" },
        { english: "Last week", russian: "На прошлой неделе", transliteration: "Na proshloy nedele" },
        { english: "Next week", russian: "На следующей неделе", transliteration: "Na sleduyushchey nedele" },
        { english: "This month", russian: "В этом месяце", transliteration: "V etom mesyatse" },
        { english: "Last month", russian: "В прошлом месяце", transliteration: "V proshlom mesyatse" },
        { english: "Next month", russian: "В следующем месяце", transliteration: "V sleduyushchem mesyatse" },
        { english: "Year", russian: "Год", transliteration: "God" },
    ],
    
    colors: [
        { english: "White", russian: "Белый", transliteration: "Belyy" },
        { english: "Black", russian: "Черный", transliteration: "Chernyy" },
        { english: "Red", russian: "Красный", transliteration: "Krasnyy" },
        { english: "Blue", russian: "Синий", transliteration: "Siniy" },
        { english: "Green", russian: "Зеленый", transliteration: "Zelenyy" },
        { english: "Yellow", russian: "Желтый", transliteration: "Zheltiy" },
        { english: "Orange", russian: "Оранжевый", transliteration: "Oranzhevy" },
        { english: "Purple", russian: "Фиолетовый", transliteration: "Fioletovyy" },
        { english: "Brown", russian: "Коричневый", transliteration: "Korichnevyy" },
        { english: "Pink", russian: "Розовый", transliteration: "Rozovyy" },
        { english: "Gray", russian: "Серый", transliteration: "Seryy" },
        { english: "Gold", russian: "Золотой", transliteration: "Zolotoy" },
        { english: "Silver", russian: "Серебряный", transliteration: "Serebryanyy" },
    ],
    
    familyMembers: [
        { english: "Mother", russian: "Мама", transliteration: "Mama" },
        { english: "Father", russian: "Папа", transliteration: "Papa" },
        { english: "Brother", russian: "Брат", transliteration: "Brat" },
        { english: "Sister", russian: "Сестра", transliteration: "Sestra" },
        { english: "Grandmother", russian: "Бабушка", transliteration: "Babushka" },
        { english: "Grandfather", russian: "Дедушка", transliteration: "Dedushka" },
        { english: "Son", russian: "Сын", transliteration: "Syn" },
        { english: "Daughter", russian: "Дочь", transliteration: "Doch" },
        { english: "Uncle", russian: "Дядя", transliteration: "Dyadya" },
        { english: "Aunt", russian: "Тетя", transliteration: "Tetya" },
        { english: "Cousin", russian: "Двоюродный брат", transliteration: "Dvoyurodnyy brat", gender: 'male' },
        { english: "Cousin", russian: "Двоюродная сестра", transliteration: "Dvoyurodnaya sestra", gender: 'female' },
        { english: "Nephew", russian: "Племянник", transliteration: "Plemiannik" },
        { english: "Niece", russian: "Племянница", transliteration: "Plemiannitsa" },
        { english: "Wife", russian: "Жена", transliteration: "Zhena" },
        { english: "Husband", russian: "Муж", transliteration: "Muzh" },
    ],
    
    commonOccupations: [
        { english: "Teacher", russian: "Учитель", transliteration: "Uchitel" },
        { english: "Doctor", russian: "Врач", transliteration: "Vrach" },
        { english: "Engineer", russian: "Инженер", transliteration: "Inzhener" },
        { english: "Nurse", russian: "Медсестра", transliteration: "Medsestra" },
        { english: "Driver", russian: "Водитель", transliteration: "Voditel" },
        { english: "Lawyer", russian: "Юрист", transliteration: "Yurist" },
        { english: "Cook/Chef", russian: "Повар", transliteration: "Povar" },
        { english: "Artist", russian: "Художник", transliteration: "Khudozhnik" },
        { english: "Scientist", russian: "Ученый", transliteration: "Uchenyy" },
        { english: "Police Officer", russian: "Полицейский", transliteration: "Politsiyskiy" },
    ],
    
    descriptions: [
        { english: "Tall", russian: "Высокий", transliteration: "Vysokiy" },
        { english: "Short", russian: "Низкий", transliteration: "Nizkiy" },
        { english: "Young", russian: "Молодой", transliteration: "Molodoy" },
        { english: "Old", russian: "Старый", transliteration: "Staryy" },
        { english: "Beautiful", russian: "Красивый", transliteration: "Krasivyy" },
        { english: "Handsome", russian: "Красивый (used for men)", transliteration: "Krasivyy" },
        { english: "Ugly", russian: "Уродливый", transliteration: "Urodlivyy" },
        { english: "Thin", russian: "Худой", transliteration: "Khudoy" },
        { english: "Fat", russian: "Толстый", transliteration: "Tolstyy" },
        { english: "Strong", russian: "Сильный", transliteration: "Sil'nyy" },
        { english: "Weak", russian: "Слабый", transliteration: "Slabyy" },
    ],
    
    commonVerbs: [
        { english: "Eat", russian: "Есть", transliteration: "Est'" },
        { english: "Go", russian: "Идти", transliteration: "Idti" },
        { english: "See", russian: "Видеть", transliteration: "Videt'" },
        { english: "Do/Make", russian: "Делать", transliteration: "Delat'" },
        { english: "Can (be able to)", russian: "Мочь", transliteration: "Moch'" },
        { english: "Have", russian: "Иметь", transliteration: "Imet'" },
        { english: "Speak/Talk", russian: "Говорить", transliteration: "Govorit'" },
        { english: "Understand", russian: "Понимать", transliteration: "Ponimat'" },
        { english: "Come", russian: "Приходить", transliteration: "Prihodit'" },
        { english: "Think", russian: "Думать", transliteration: "Dumat'" },
        { english: "Know", russian: "Знать", transliteration: "Znat'" },
        { english: "Live", russian: "Жить", transliteration: "Zhit'" },
        { english: "Work", russian: "Работать", transliteration: "Rabotat'" },
        { english: "Like/Love", russian: "Любить", transliteration: "Lyubit'" },
        { english: "Help", russian: "Помогать", transliteration: "Pomogat'" },
        { english: "Play", russian: "Играть", transliteration: "Igrat'" },
        { english: "Read", russian: "Читать", transliteration: "Chitat'" },
        { english: "Write", russian: "Писать", transliteration: "Pisat'" },
        { english: "Sit", russian: "Сидеть", transliteration: "Sidet'" },
        { english: "Stand", russian: "Стоять", transliteration: "Stoyat'" },
    ],
    
    commonAdjectives: [
        { english: "Big", russian: "Большой", transliteration: "Bol'shoy" },
        { english: "Small", russian: "Маленький", transliteration: "Malen'kiy" },
        { english: "Interesting", russian: "Интересный", transliteration: "Interesnyy" },
        { english: "Boring", russian: "Скучный", transliteration: "Skuchnyy" },
        { english: "Good", russian: "Хороший", transliteration: "Khoroshiy" },
        { english: "Bad", russian: "Плохой", transliteration: "Plokhoy" },
        { english: "New", russian: "Новый", transliteration: "Novyy" },
        { english: "Delicious", russian: "Вкусный", transliteration: "Vkusnyy" },
        { english: "Disgusting", russian: "Отвратительный", transliteration: "Otvratitel'nyy" },
        { english: "Easy", russian: "Легкий", transliteration: "Legkiy" },
        { english: "Difficult", russian: "Сложный", transliteration: "Slozhnyy" },
        { english: "Fast", russian: "Быстрый", transliteration: "Bystryy" },
        { english: "Slow", russian: "Медленный", transliteration: "Medlennyy" },
        { english: "Bright", russian: "Яркий", transliteration: "Yarkiy" },
        { english: "Dark", russian: "Темный", transliteration: "Temnyy" },
    ],
    
    foods: [
        { english: "Bread", russian: "Хлеб", transliteration: "Khleb" },
        { english: "Butter", russian: "Масло", transliteration: "Maslo" },
        { english: "Eggs", russian: "Яйца", transliteration: "Yaytsa" },
        { english: "Milk", russian: "Молоко", transliteration: "Moloko" },
        { english: "Cheese", russian: "Сыр", transliteration: "Syr" },
        { english: "Potato", russian: "Картофель", transliteration: "Kartofel'" },
        { english: "Chicken", russian: "Курица", transliteration: "Kuritsa" },
        { english: "Fish", russian: "Рыба", transliteration: "Ryba" },
        { english: "Soup", russian: "Суп", transliteration: "Sup" },
        { english: "Porridge", russian: "Каша", transliteration: "Kasha" },
        { english: "Sausage", russian: "Колбаса", transliteration: "Kolbasa" },
        { english: "Salad", russian: "Салат", transliteration: "Salat" },
    ],
    
    drinks: [
        { english: "Tea", russian: "Чай", transliteration: "Chay" },
        { english: "Coffee", russian: "Кофе", transliteration: "Kofe" },
        { english: "Mineral Water", russian: "Минеральная вода", transliteration: "Mineral'naya voda" },
        { english: "Juice", russian: "Сок", transliteration: "Sok" },
        { english: "Beer", russian: "Пиво", transliteration: "Pivo" },
        { english: "Wine", russian: "Вино", transliteration: "Vino" },
        { english: "Vodka", russian: "Водка", transliteration: "Vodka" },
    ],
    
    phrasesForOrderingAtARestaurant: [
        { english: "I would like to order...", russian: "Я бы хотел заказать...", transliteration: "Ya by khotel zakazat'..." },
        { english: "Could I have the menu, please?", russian: "Можно меню, пожалуйста?", transliteration: "Mozhno menyu, pozhaluysta?" },
        { english: "A table for two, please.", russian: "Столик на двоих, пожалуйста.", transliteration: "Stolik na dvoikh, pozhaluysta." },
        { english: "What do you recommend?", russian: "Что вы рекомендуете?", transliteration: "Chto vy rekomenduyete?" },
        { english: "Could I have the bill, please?", russian: "Можно счет, пожалуйста?", transliteration: "Mozhno schet, pozhaluysta?" },
        { english: "I am allergic to...", russian: "У меня аллергия на...", transliteration: "U menya allergiya na..." },
        { english: "Is this dish spicy?", russian: "Это блюдо острое?", transliteration: "Eto blyudo ostroe?" },
        { english: "Can I have some water, please?", russian: "Можно воды, пожалуйста?", transliteration: "Mozhno vody, pozhaluysta?" },
        { english: "Another one, please.", russian: "Еще один, пожалуйста.", transliteration: "Eshche odin, pozhaluysta." },
        { english: "A cup of coffee, please.", russian: "Чашку кофе, пожалуйста.", transliteration: "Chashku kofe, pozhaluysta." },
        { english: "I'll have a sandwich.", russian: "Я возьму бутерброд.", transliteration: "Ya voz'mu buterbrod." },
        { english: "Please give me this.", russian: "Пожалуйста, дайте мне это.", transliteration: "Pozhaluysta, dayte mne eto." },
        { english: "How much is the bread?", russian: "Сколько стоит хлеб?", transliteration: "Skol'ko stoit khleb?" },
        { english: "Could I get a glass of juice?", russian: "Можно стакан сока?", transliteration: "Mozhno stakan soka?" },
    ],
    
    namesOfPlaces: [
        { english: "Home", russian: "Дом", transliteration: "Dom" },
        { english: "School", russian: "Школа", transliteration: "Shkola" },
        { english: "University", russian: "Университет", transliteration: "Universitet" },
        { english: "Hospital", russian: "Больница", transliteration: "Bol'nitsa" },
        { english: "Pharmacy", russian: "Аптека", transliteration: "Apteka" },
        { english: "Store/Shop", russian: "Магазин", transliteration: "Magazin" },
        { english: "Market", russian: "Рынок", transliteration: "Rynok" },
        { english: "Park", russian: "Парк", transliteration: "Park" },
        { english: "Museum", russian: "Музей", transliteration: "Muzei" },
        { english: "Theater", russian: "Театр", transliteration: "Teatr" },
        { english: "Cinema", russian: "Кинотеатр", transliteration: "Kinoteatr" },
        { english: "Library", russian: "Библиотека", transliteration: "Biblioteka" },
        { english: "Church", russian: "Церковь", transliteration: "Tserkov'" },
        { english: "Police Station", russian: "Полицейский участок", transliteration: "Politsiyskiy uchastok" },
        { english: "Restaurant", russian: "Ресторан", transliteration: "Restoran" },
        { english: "Café", russian: "Кафе", transliteration: "Kafe" },
        { english: "Hotel", russian: "Гостиница", transliteration: "Gostinitsa" },
        { english: "Bank", russian: "Банк", transliteration: "Bank" },
        { english: "Office", russian: "Офис", transliteration: "Ofis" },
        { english: "Gym", russian: "Спортзал", transliteration: "Sportzal" },
    ],
    
    directionWords: [
        { english: "Left", russian: "Налево", transliteration: "Nalevo" },
        { english: "Right", russian: "Направо", transliteration: "Napravo" },
        { english: "Straight", russian: "Прямо", transliteration: "Pryamo" },
        { english: "Back", russian: "Назад", transliteration: "Nazad" },
        { english: "Up", russian: "Вверх", transliteration: "Vverkh" },
        { english: "Down", russian: "Вниз", transliteration: "Vniz" },
        { english: "North", russian: "Север", transliteration: "Sever" },
        { english: "South", russian: "Юг", transliteration: "Yug" },
        { english: "East", russian: "Восток", transliteration: "Vostok" },
        { english: "West", russian: "Запад", transliteration: "Zapad" },
    ],
    
    directionPhrases: [
        { english: "Where is the nearest pharmacy?", russian: "Где ближайшая аптека?", transliteration: "Gde blizhayshaya apteka?" },
        { english: "How do I get to the museum?", russian: "Как мне добраться до музея?", transliteration: "Kak mne dobrat'sya do muzei?" },
        { english: "Is it far from here?", russian: "Это далеко отсюда?", transliteration: "Eto daleko otsyuda?" },
        { english: "Can you show me on the map?", russian: "Можете показать на карте?", transliteration: "Mozhete pokazat' na karte?" },
    ],
    
    timeRelatedWordsAndPhrases: [
        { english: "What time is it?", russian: "Который час?", transliteration: "Kotoryy chas?" },
        { english: "It's one o'clock.", russian: "Сейчас один час.", transliteration: "Seychas odin chas." },
        { english: "Minute", russian: "Минута", transliteration: "Minuta" },
        { english: "Hour", russian: "Час", transliteration: "Chas" },
        { english: "Day", russian: "День", transliteration: "Den'" },
        { english: "Week", russian: "Неделя", transliteration: "Nedelya" },
        { english: "Month", russian: "Месяц", transliteration: "Mesyats" },
        { english: "Year", russian: "Год", transliteration: "God" },
        { english: "Morning", russian: "Утро", transliteration: "Utro" },
        { english: "Afternoon", russian: "День", transliteration: "Den'" },
        { english: "Evening", russian: "Вечер", transliteration: "Vecher" },
        { english: "Night", russian: "Ночь", transliteration: "Noch'" },
    ],
    
    weatherTermsAndDescriptions: [
        { english: "Weather", russian: "Погода", transliteration: "Pogoda" },
        { english: "Sunny", russian: "Солнечно", transliteration: "Solnechno" },
        { english: "Cloudy", russian: "Облачно", transliteration: "Oblachno" },
        { english: "Rainy", russian: "Дождливо", transliteration: "Dozhd'livo" },
        { english: "Snowy", russian: "Снежно", transliteration: "Snezhno" },
        { english: "Windy", russian: "Ветрено", transliteration: "Vetreno" },
        { english: "Stormy", russian: "Бурно", transliteration: "Burno" },
        { english: "Foggy", russian: "Туманно", transliteration: "Tumanno" },
        { english: "Cold", russian: "Холодно", transliteration: "Kholodno" },
        { english: "Hot", russian: "Жарко", transliteration: "Zharko" },
        { english: "Warm", russian: "Тепло", transliteration: "Teplo" },
        { english: "Cool", russian: "Прохладно", transliteration: "Prokhladno" },
        { english: "Temperature", russian: "Температура", transliteration: "Temperatura" },
        { english: "Degree", russian: "Градус", transliteration: "Gradus" },
    ],
    
    askingAboutWeather: [
        { english: "What's the weather like today?", russian: "Какая сегодня погода?", transliteration: "Kakaya segodnya pogoda?" },
        { english: "Will it rain tomorrow?", russian: "Завтра будет дождь?", transliteration: "Zavtra budet dozhd'?" },
        { english: "Is it cold outside?", russian: "На улице холодно?", transliteration: "Na ulitse kholodno?" },
    ]
    
};

export const intermediateWordLists = {
    travelAndTransportation: {
        airportAndTrainStation: [
            { english: "Airport", russian: "Аэропорт", transliteration: "Aeroport" },
            { english: "Train Station", russian: "Вокзал", transliteration: "Vokzal" },
            { english: "Ticket", russian: "Билет", transliteration: "Bilet" },
            { english: "Passport", russian: "Паспорт", transliteration: "Pasport" },
            { english: "Luggage", russian: "Багаж", transliteration: "Bagazh" },
            { english: "Departure", russian: "Отправление", transliteration: "Otpravlenie" },
            { english: "Arrival", russian: "Прибытие", transliteration: "Pribytie" },
            { english: "Check-In", russian: "Регистрация", transliteration: "Registratsiya" },
            { english: "Customs", russian: "Таможня", transliteration: "Tamozhnya" },
            { english: "Security Check", russian: "Контроль безопасности", transliteration: "Kontrol' bezopasnosti" },
            { english: "Gate", russian: "Выход на посадку", transliteration: "Vykhod na posadku" },
            { english: "Boarding", russian: "Посадка", transliteration: "Posadka" },
            { english: "Flight", russian: "Рейс", transliteration: "Reys" },
            { english: "Delayed", russian: "Задержан", transliteration: "Zaderzhan" },
            { english: "Cancelled", russian: "Отменен", transliteration: "Otmenen" },
        ],
        commonPhrasesForBuyingTickets: [
            { english: "One ticket to Moscow, please.", russian: "Один билет до Москвы, пожалуйста.", transliteration: "Odin bilet do Moskvy, pozhaluysta." },
            { english: "Where can I buy a ticket?", russian: "Где я могу купить билет?", transliteration: "Gde ya mogu kupit' bilet?" },
            { english: "Is this seat available?", russian: "Это место свободно?", transliteration: "Eto mesto svobodno?" },
            { english: "I’d like to book a seat by the window.", russian: "Я бы хотел забронировать место у окна.", transliteration: "Ya by khotel zabronirovat' mesto u okna." },
        ],
        vocabularyForAskingForDirections: [
            { english: "Where is...?", russian: "Где находится...?", transliteration: "Gde nakhoditsya...?" },
            { english: "How do I get to...?", russian: "Как мне добраться до...?", transliteration: "Kak mne dobratsya do...?" },
            { english: "Is it far?", russian: "Это далеко?", transliteration: "Eto daleko?" },
            { english: "To the left.", russian: "Налево.", transliteration: "Nalevo." },
            { english: "To the right.", russian: "Направо.", transliteration: "Napravo." },
            { english: "Straight ahead.", russian: "Прямо.", transliteration: "Pryamo." },
            { english: "Map", russian: "Карта", transliteration: "Karta" },
        ],
        commonPhrasesUsedDuringTravel: [
            { english: "Can you show me on the map?", russian: "Можете показать на карте?", transliteration: "Mozhete pokazat' na karte?" },
            { english: "I need a taxi.", russian: "Мне нужно такси.", transliteration: "Mne nuzhno taksi." },
            { english: "How much does it cost?", russian: "Сколько это стоит?", transliteration: "Skol'ko eto stoit?" },
            { english: "Please stop here.", russian: "Остановитесь здесь, пожалуйста.", transliteration: "Ostanovites' zdes', pozhaluysta." },
            { english: "I am lost.", russian: "Я потерялся.", transliteration: "Ya poteryalsya/poteryalas'.", gender: "male"},
            { english: "I am lost.", russian: "Я потерялась.", transliteration: "Ya poteryalsya/poteryalas'.", gender: "female" },
            { english: "Does this train/bus go to...?", russian: "Этот поезд/автобус идет до...?", transliteration: "Etot poyezd/avtobus idet do...?" },
        ],
    },
}